#!/bin/bash

echo "Pre-push hook started"

# Check if we are pushing to the deploy branch
while read local_ref local_sha remote_ref remote_sha
do
  echo "Local Ref: $local_ref"
  echo "Local SHA: $local_sha"
  echo "Remote Ref: $remote_ref"
  echo "Remote SHA: $remote_sha"

  if [[ $remote_ref == "refs/heads/deploy" ]]; then
    echo "Deploying to public branch..."

    git pull

    # Create a temporary directory
    TMP_DIR=$(mktemp -d)

    # Capture the last commit message from the deploy branch
    LAST_COMMIT_MSG=$(git log -1 --pretty=reference)

    # Copy docs content to temporary directory
    cp -r docs/* $TMP_DIR/

    # Checkout public branch
    git checkout public

    # Remove old files and copy new files from temporary directory
    git rm -r *
    cp -r $TMP_DIR/* .

    # Commit and push changes to public branch
    git add .
    git commit -m "$LAST_COMMIT_MSG"
    git push origin public

    # Switch back to deploy branch
    git checkout deploy
  fi
done
