website:
  title: "Yuxi on the Wired"
  description: "Personal website of Yuxi Liu"
  image: img/blog icon.jpg
  site-url: https://yuxi-liu-wired.github.io/

  favicon: img/favicon.ico
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/favicon.ico
    
    # your sub-pages
    left:
      - text: "Blog"
        href: blog/index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "About"
        href: about/index.qmd
      # - text: "CV"
      #   href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: folder-symlink
        href: https://bair.berkeley.edu/
      # - icon: wikipedia
      #   href: 
      # - icon: linkedin
      #   href: https://www.linkedin.com/in/yuxi-liu-78b947277/
      - icon: envelope
        aria-label: email
        href: "mailto:yuxi.liu.1995@gmail.com"  
  
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">Yuxi on the Wired</span>
    right: |
      <span class="faux-block">Everything © <a href="https://www.apache.org/licenses/LICENSE-2.0.html">Apache License 2.0</a></span>
  open-graph: true
  twitter-card: true

project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "404.qmd"
    - "blog/**/*.qmd"
    - "about/**/*.qmd"
    - "projects/**/*.qmd"

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: auto

format:
  html:
    fontsize: 1.1em
    theme: 
      light: flatly
      dark: darkly
      # light: html/theme-light.scss
      # dark: html/theme-dark.scss
    toc: true
    toc-location: left
    code-tools: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true

bibliography: static/references.bib
