---
title: "Commentaries and essays by Liu Cixin"
author: "Liu Cixin"
date: "1998-06"
categories: [China, fun, scifi]
format:
 html:
  toc: true
  resources:
    - "figure/**"
description: "The world, the universe, and sci-fi, as he sees it. Translated from the anthology *The Best Earth in the Worst Universe* (2015)"
status: "finished"
confidence: "log"
importance: 2
---

These are essays from *The Best Earth in the Worst Universe: A Collection of Liu Cixin's Science Fiction Comments and Essays* (最糟的宇宙，最好的地球: 刘慈欣科幻随笔集), published in 2015, just after Liu Cixin became internationally acclaimed.

He pulls no punches, and I suspect they will never be translated for a mass audience. To see why, consider just the [interview](#liu-jiang-debate-2007), where he claimed to be a "fanatic of Technologism". Such political incorrectness appears here and there as well, but he is honest and consistent in his viewpoint, and many in China, especially the [Industrial Party](https://en.wikipedia.org/wiki/Industrial_Party_(China)), believe in his vision.

I translated with the help of DeepL. Those cover about 1/4 of the book. The rest of the book seems hardly of general interest.

## Electronic poet (2001)

Posted on 2001-01-07 at the Tsinghua University BBS, Sci-Fi section.

The program is available for download [here](figure/electronic_poet.exe).

```{txt}
***********************************
Work No. 75509
**************************************
I face the black artist and the thorny waves
I see the dazzling mind taking a nap, the program code slamming the playground
In this olive green playground, there are no trucks, only butterflies
I want to take drugs, I want to turn yellow weakly
I face the bright winter snow and the hyperbolic glow
I see the blue breasts floating, the soap listening to the walrus
In this weak spring rain, there is no Beethoven, only mother
I want to rise, I want to sing with breathing
I face the wide boat and the transparent microwave beam
I see the dead fishing boat calling, the distilled water shoveling the sheep
In this porous moss, there is no Eve, only the teacher
I want to hibernate, I want to shine hatefully
I face the bloody epic and the distant fire
I saw the vibrant battleships in silence, the transparent skirts caressing the playground
In this curvilinear struggler, there is no moonlight dance, only wind and sand
I want to swing, I want to panic roughly
```

What did you see? No, no, don't get me wrong, this is not what I wrote.

Dear sci-fi friends, the new millenium is coming, you must want to bring some local specialties from this century. After thinking about it, I thought of the same thing: poets. Poets are certainly not born of this century, but they are certainly to go extinct in this century. The poetic century has disappeared forever. In the new century, even if there are poets, they must be as rare as dinosaur eggs.

This spring, I read *The First Sally (A) or Trurl's Electronic Bard* by Stanisław Lem (a masterpiece, I hope everyone will read it). Then I buried my head in front of the computer and worked hard for a week, turning Lem's fantasy into reality at least in part: I created an electronic poet, or as Gibson said in *Neuromancer*, a poet's "construct".

Both I and the "construct" are self-aware, and I don't want to compare with Li Bai and Percy Bysshe Shelley, but I can definitely compare with modern poets. It is said that modern poetry emphasizes obscurity and freedom, so let them compare with my CPU to see who is more obscure and free!

Maybe when reading these poems, some people feel that the poet's senses are deranged, but isn't a "systematic derangement of the senses" what modern poetry pursues? More importantly, this is computer-style poetry, which humans cannot imitate! If you don't believe me, try, and you will have heart failure in a short time.

But the biggest advantage of the electronic poet is speed. According to the latest measurement, the poetry output is 200 lines/second (non-rhyming) or 150 lines/second (rhyming). This is the test result on my old Pentium 166 MMX machine. If it is on Pentium III 500, haha. The poetry production method is absolutely automatic. Except for telling the number of lines, no human intervention is required.

The day before yesterday, I had a party with friends and asked him to write a 300,000-line long poem to liven up the party. He was really good. He wrote it before he finished half a bottle of Erguotou liquor. Unfortunately, I didn't even finish appreciating one thousandth of it. But the poet guaranteed with his mathematical personality and the `RAND()` function that there would be no repeated line in these 300,000 lines! The electronic poet is programmed with Visual Foxpro, which contains 5 program modules, 6 word libraries, and a grammar library. I just slimmed it down and removed all GUI stuff. Although it is not beautiful, it looks like DOS, but it is very slim, only 125KB. I would like to give this as a new century gift to all my sci-fi comrades. If anyone is willing to send me a nice new century greeting card (`ndjsjl@public.yq.sx.cn`) by email, I will send you the `poet.exe`. (The original code is not compiled, and runs under `VF3.0` and above, with the main control module code page)

Imagine when you are old, you and your few great-grandchildren stand under the eco-dome, and twenty artificial suns cast bright light from space. At this time, you talk to your few great-grandchildren about our romantic and passionate era, and you lower your voice to tell them that there was such a thing as night, such a thing as the moon, such a thing as trees, and such a thing as grass... When they stare at each other in disbelief, you would then tell them that there is also such a thing as poetry! Before you know it, tons of new poems torrent out of the Pentium-300000 wrist-computer!! Think about the expressions of your few great-grandchildren, haha.

Please enjoy a few more poems below. I am afraid of being too superficial, so I dare not post too many,
let alone long poems.


```{txt}
********************************
Work No. 28611
***********************************
Asteroids are called
Around the solid, there are only gelatinous rice fields
No, I don't want to fly!!
I miss

Trigonometric functions are watched!
Around Andromeda, there are only living giant rivers
No, I don't want to devour myself!!
I precipitate

Dragonflies are pinched!
Around the Orient Express, there are only wagging bows and arrows
No, I don't want to smoke!!
I talk

The confinement room is warned!
Around the sword, there is only the squeak of time
No, I don't want to sleepwalk!!
I rot
```

[Other poems are omitted, as they are in the same nonsense style.]

## Religious feeling in sci-Fi (2001)

Posted on 2001-02-22 at the Tsinghua University BBS, Sci-Fi section.

At present, Chinese science fiction lacks a lot of things, one of which has never been noticed or mentioned, but is extremely important.

Chinese science fiction lacks religious feelings.

First of all, I am a firm atheist. At the same time, we know that science and religion are incompatible, and science fiction and religion are also incompatible. However, some scholars believe that the reason why modern natural science was born in the West has something to do with the strong religious feelings in Western culture. This is a topic that can't be explained even with a huge book that presses people to death, so I'm not going to delve into it here, and I'll just talk about religious feelings in sci-fi. Note that it's not religion that's being talked about here, it's religious feeling, and it's not the kind of feeling you have for God, it's atheistic, and it's not as sophisticated as Spinoza or whatever.

The religious feeling of sci-fi is a deep sense of awe at the grand mystery of the universe.

Consider the following two depictions, one of which depicts police chasing criminals across the stars:

> The police ship clung to the smuggling ship, skimming planet after planet. Every planet, the smuggling ship captain carefully observed the planet's terrain, he was eager to find a planet with suitable terrain to land, with the pursuers of the duel, but has not been able to find, had to turn back to look at the police spaceship closer and closer, gritted his teeth and continued to fly forward...

The second depicts a head-on encounter between two giant starships traveling at a fraction of the speed of light:

> "They just missed with us!", shouted the navigator on board ship XX, and at the sound of his voice, the ship's pilot jerked the control lever back, and the XX turned over in a somersault, turned 180 degrees, and chased after the ship...
Both are paraphrased from domestic science fiction. The former gives the reader the impression that the universe is not much bigger than a small town in a cop movie, and that the planets in space are just like storefronts on the side of the thoroughfare. The latter makes the reader feel that an interstellar spacecraft flying at relativistic speeds behaves much like a taxicab on the street. In such a depiction, the author is blind to the cosmic grandeur. It is not that such a depiction is totally unacceptable; such episodes are often found in many of the world's most famous novels, such as *Interstellar Detective*[^interstellar-detective] and so on. For these allegorical novels, the universe is just a tool to develop the plot. But the main attraction of science fiction is not that.

[^interstellar-detective]: No idea what this work is.

A huge spaceship, flying in the dark silence of space to a distant goal, will take 2000 years to accelerate, maintain cruising speed for 3000 years, and then 2000 years to decelerate. Generations of people has been born and died. The earth has become an ancient vague dream. The spaceship archaeologists can no longer unearth evidence, out of the vast strata of the spaceship, that Earth once existed. that distant destination has become a myth that has been passed down for thousands of years, a religious phantasy. Generation after generation, people don't know where they came from; generation after generation, people don't know where they are going. Most people believe that the spaceship is an eternal world that has existed and will exist forever, and only a small number of wise men, convinced of the existence of the destination, look day and night into the infinitely deep cosmic abyss in front of the spaceship... This is the theme of several Western science fiction novels. What do you feel in such a depiction? Is it the far-reaching vastness of the universe, or the shortness of life. Perhaps, you thus look down on the whole history of mankind from the perspective of the universe from afar with the eyes of God, and you find with emotion that our civilization is only a tiny grain of sand in the cosmic desert of space and time.

One might think that FTL technology and space-time leapfrogging depicted in science fiction would inevitably make the universe perceptually smaller, just as airplanes and modern communication networks have made the earth smaller. This is true. If FTL technology is really possible, perhaps the universe will one day be just a village in human senses, just as the global village is today. But we're talking about novels, think about it, there are two novels, one depicting Columbus in the vast Atlantic Ocean, searching with great fear and little hope for the new land of his dreams, the other depicting a company clerk traveling by plane from Paris to New York City on a business trip, which one do you want to read? Meanwhile, the Earth hasn't actually been shrunk; vast expanses of earth and ocean still exist, and modern man is still experiencing the romantic thrill of ancient man's trek across the surface of this planet through hiking and the [America's Cup race](https://en.wikipedia.org/wiki/America's_Cup). There's no reason for science fiction to shrink the universe into villages when most people can't even fly out of the atmosphere. What's more, even in the FTL era, the universe as a whole is still full of great mystery and shock value.

Frederick Pohl's *Father of the Stars* describes a billionaire who has spent his life building dozens of gigantic spaceships, all with conventional rocket engines, which carry tens of thousands of people into the vastness of space to open up a new living space for mankind. A few decades after the departure of these spaceships, science on Earth made FTL spaceships a reality, and such spaceships, carrying the hero in his twilight years, took only a day or two to catch up with those traditional spaceships that had departed a few decades earlier, making the feat that the hero and tens of thousands of pioneers had carried out with all their lives a meaningless tragedy. In this novel, Pohl uses the contrast between the two technologies to create a simultaneous feeling of the vastness of outer space, the tragedy of the pioneers, and the relentlessness of fate.

The pinnacle of depictions of vast time-space belongs to Arthur C. Clarke's *2001*, The fear, loneliness and awe of human beings in front of the mysterious universe expressed in the novel, which carves into the readers' heart and soul, is unforgettable for the rest of their lives. I remember twenty years ago that winter night, after reading that book, I went out to look up at the night sky, and suddenly felt that everything around me had disappeared, and the earth under my feet became a pure geometric plane with infinite extension of snow-white and smooth, and on this infinite two-dimensional plane, under the magnificent starry night sky, there stood I alone, facing this vast mystery that the human mind could not grasp... Since then, the starry sky looked different in my eyes. The feeling is like leaving the pool to see the sea. This made me deeply appreciate the power of science fiction.

In the busy and practically-minded modern society, people's eyes are mostly confined in boxes, and they seldom look at space. I once asked ten people whether the moon would come out in the daytime, and except for one person who was a bit hesitant, the others were very sure that it would not. Modern society has also made people numb to astronomical numbers. No one seriously tries to *visualize* a light years in the world, and the cosmic scale of 15 billion light years is not much different from 15 billion kilometers in the minds of most people. Numbness to the universe pervades society. The mission of science fiction is to broaden and deepen people's minds, and if readers stop on their way home from work and look up at the starry sky for a while, the novel is a great success. Unfortunately, our science fiction is currently in this same numbness to a considerable degree. This is probably due to two reasons.

The first reason is the science fiction philosophy. It is believed that science fiction, like mainstream literature, depicts the relationship between people. Under this concept, the universe is only a prop, a background and an accompaniment in the works. Undeniably, many excellent works have been produced under this concept, but the greatest advantage and charm of science fiction is the depiction of the relationship between human beings and the universe. The universe should be as important a protagonist in science fiction as man. The reason why the two sequels of *2001* -- *2010* and *2061* -- are not so successful, is that the authors have shifted their focus to depicting the relationships of human society and destroyed the mystery and ethereal nature of the universe that was established in *2001*.

Truly gut-feeling the universe is hard. Standing on the roof of a tall building, we have the feeling of being high above the ground; sitting on a hot steam balloon rising to a thousand meters, this feeling is even stronger and dizzying; but if we look down from an airliner flying at 20,000 meters, this sense of altitude is rather diminished; looking down from a space shuttle operating in an orbit several hundred kilometers high, we may need to borrow more or less from our imaginations in order to get a sense of altitude; and looking at Earth from the moon, which is more than 300,000 kilometers away, we can't get a sense of altitude in any case. When we look at the Earth from the Moon, which is more than 300,000 kilometers away, we can't get any sense of height in any case. It just looks like a lovely blue toy. It is very difficult for humans to perceive the mega scale. The grandeur of the universe is also manifested in the opposite microscopic direction, which is even more difficult for human perception. At the same time, modern science has reached a very deep level of understanding about the macroscopic and microscopic aspects of the universe, and the description of the universe by science is not only beyond our imagination, but even beyond what we could have imagined. To truly appreciate the grandeur of the universe and to show this grandeur in novels requires imagination beyond ordinary people, high literary-technical skills, and a deep understanding of the forefront of modern science. It is the perpetual grand challenge and goal for science fiction.

But all of this presupposes the kind of religious feeling that science fiction authors have for the universe.

A philosophy professor once said that the first introductory lesson for philosophy freshmen should be to look up at the stars for long time late at night. I think this should be, even more so, the first lesson for science fiction authors, as it will enable them to really find the feeling of science fiction deep inside.

The grand and mysterious universe is the God of science fiction, and the Gospel of Scifism is:

> Feel the Lord's greatness, feel the Lord's depth, describe this feeling, show it to those busy people, so that they feel as you, feel the Lord's greatness and depth. Then blessed shall be you, those busy people, and Chinese science fiction.

## Acceptance speech at the 2000 Galaxy Awards (2000)

Based on the translation by Forestaller: <https://www.reddit.com/r/threebodyproblem/comments/as70eu/ot_translation_liu_cixins_acceptance_speech_at/>. Copied and fixed.

I am very glad that *The Wandering Earth* (2000) has gained the love of readers at large. This short story is part of a series I planned call "The Apocalyptic Series": based on the premise of a solar catastrophe, it describes the process of humanity's attempts at escape by various means; in descending order of the success rate of escape:

The 1st is [*Mend the Heavens*](https://en.wikipedia.org/wiki/N%C3%BCwa#N%C3%BCwa_Mends_the_Heavens), describing how humans enter the sun to fix and delay the solar catastrophe from the inside;

The 2nd is *Micro-Age* (1998);

The 3rd is *The Wandering Earth* (2000);

The 4th is *Starship Eras*, describing how humans left the solar system on spaceships, lost their targets and came to regard the spaceships as home;

The 5th is *Wandering Souls*, describing how humans broadcast their thoughts and memories to the universe before the solar catastrophe; 

And the last is very dark -- named *On Pluto we sat down and wept*, after Byron's poem *By the river of Babylon we sat down and wept* -- it describes how all hope was lost and a monument to humanity was built on Pluto, in what is more of a grim essay.[^on-pluto]

[^on-pluto]: This Plutonian "monument to humanity" appears in *Death's End*.

When you are diagnosed with cancer, the world changes in your eyes: the sky is red and the sun is blue; but when you are finally informed that it was a mis-diagnosis, when the sky turns blue and the sun turns red again, they are not the same sky and sun as before -- the world and living becomes more beautiful in your eyes, and maybe even more meaningful; this is not a feeling you can ever get from a decade's worth of books. The apocalyptic experience of an individual is a very valuable one; so what about the apocalyptic experience of all humanity? If the world suffers such a "mis-diagnosis"; then all humanity will look at our sky and sun with new eyes, treasure more greatly all things they regard as normal, and the human world will move along a more reasonable track. Only sci-fi novels can bring about this apocalyptic experience, and this is my initial purpose in planning this apocalyptic series.

Sci-fi novels can create a whole new world, where writers and readers can experience what is impossible in reality -- this is why I love sci-fi. I started writing as a sci-fi fan, without any systematic consideration of sci-fi theories. I like sci-fi with less literary elements and more sci-fi elements, and have always thought that penetrating reality and dissecting human nature is neither the mission of sci-fi novels nor its comparative advantage l- the advantage of sci-fi lies in creating an imaginary world. I used to hold a view that even I find extremist now: to tear sci-fi out from the confines of literature itself (the sci-fi bulletin board of Tsinghua University once tried to create an encyclopedia for virtual worlds, without much success). Of course, this proposal was attacked on all fronts.

I very much agree with what A-Lai [an earlier speaker] said: every writer should persist in their extremist views, while editors should hold an all-encompassing attitude towards all kinds of view; this is the only healthy environment for the development of sci-fi. But on the other hand, when sci-fi changed from a hobby into a career, I've found the need to manage many balancing acts -- this includes balancing the works for their scientific vs literary nature, profundity vs readability, sci-fi as literature vs commodities -- so my current works are a result of these ; which are more or less a betrayal of my own ideals for sci-fi. For a writer like me who has spent years trekking on the roads of sci-fi, this is also a sign of maturity.

Speaking of maturity, this happened: I took 2 day's leave to attend these Awards, but applied for it under a different reason. 2 years ago when I published my first sci-fi story, a friend advised me to keep my writing activities "underground" in the unit (I worked at); he said, "In such a basic engineering department, mistakes and errors at work are tolerable, but not immaturity -- you must never let others feel that you are immature, or else your prospects are gone.".

This friend might be thought of as having misunderstood sci-fi, just as the society at large has; but in a way this reflects how immature our sci-fi is. For example: till now, our sci-fi stories have not created a milieu of their own -- we are just writing our own stories in the many milieu created by others.

But to look at it in another way, sci-fi literature is by its very nature immature -- because it shows humanity in its childhood, filled with curiosity and fear for the vast and profound universe, as well as the urge to explore it. In the face of such a universe, human science and philosophy are very immature, and sci-fi is the only literary form available to express our scientific and philosophical immaturities; so it's no surprise that sci-fi is filled with immaturity. When human science is developed to the furthest extent and everything in the universe is discovered down to its minutia, that will be the day sci-fi dies.

Presently -- faced with the immaturity of Chinese sci-fi -- everyone in our sci-fi community is envious of the adult sci-fi readership in the US, and see it as a sign of maturity in sci-fi literature. But one must know that senility comes after maturity, and death comes after senility. The prosperity of US sci-fi is largely a result of the prosperity of its movie and TV industries, and these sci-fi movies and TV shows are but a stylistic extension of the Golden Age of sci-fi. Contemporary sci-fi literature itself in US is already deep in twilight -- full of works applying complex techniques to express dense metaphors, completely devoid of the youthful energy of the Golden Age. Many magnum opuses in recent years already have a smell of decay about them. Americans under 25 these days basically don't read sci-fi; I don't see what's to be envied about that.

We should be most envious of ourselves: our current sci-fi readership are the 8 or 9 o'clock sun, or even the 6 or 7 o'clock sun.[^clock-sun] Chinese sci-fi a market full of youth and hope, and this is what gives sci-fi writers like us confidence and strength -- compared to this, a little immaturity is really nothing.

[^clock-sun]: 
    > The world is yours, as well as ours, but in the last analysis, it is yours. You young people, full of vigor and vitality, are in the bloom of life, like the sun at eight or nine in the morning. Our hope is placed on you. The world belongs to you. China's future belongs to you.
    > 
    > -- Mao Zedong, Quotations from Chairman Mao Tse-tung, Talk at a meeting with Chinese students and trainees in Moscow (November 17, 1957).

Some research show that many animals have language and deductive abilities, some of whom can make tools, and even a minority who has writing; but no evidence shows that animals can imagine (what does not exist), so imagination is the only difference between humanity and animals -- and our sci-fi fans here today are the most vibrant expression of that.

Thank you, everybody!

## Several books on my sci-fi journey (2007)

Source: 我的科幻之路上的几本书, 《南方周末》2007年9月13日 -- *Southern Weekend*, September 13, 2007

Books affect everyone in many ways, but it's the ones that determine one's path in life that are the most important, and as a sci-fi author, I'd like to list just the ones that set me on the path to sci-fi.

Jules Verne's novels about big machines. Jules Verne's science fiction novels are divided into two major categories in terms of the objects depicted, one is scientific adventure novels, and the other is novels depicting big machines, with the latter having more sci-fi content, mainly including Twenty Thousand Leagues Under the Sea, Propeller Island, From the Earth to the Moon, and so on. The big machines appearing in this kind of novels are all based on the steam technology and primary electric technology of the 18th and 19th centuries, crude and clumsy, which are the symbols of the age of technological childhood, and there is a kind of childlike innocence and childish beauty.

In Verne's time, science began to be transformed into technology and started the process of comprehensively influencing social life. What these big machines show is the kind of naive surprise when human beings first saw the miracle of technology, and this feeling is the very soil for science fiction to germinate and grow. Even today, the beauty of the big machines of the 19th century has not disappeared, and the specific manifestation of this is the steampunk theme that has appeared in science fiction literature in recent years, in which this kind of science fiction work shows not the future that we modern people imagine, but the present that people in the past (mostly the end of the 18th century and the first half of the 19th century) imagined. In steampunk movies and television, we can see big steam-driven machines, crudely shaped flying machines like cruisers, intricate copper piping and antique gauges everywhere. Steampunk is an imagined continuation of the era of big machines in Verne's work, and it shows a nostalgic warmth in addition to the beauty of big machines.

Arthur C. Clarke's *2001, A Space Odyssey* is another type of science fiction, the same techno-science fiction, but it is at the opposite end of the genre from Verne's big machine novels, with the latter depicting technology that is one step forward from reality, and the former depicting ethereal worlds that tend to be ultimate in both time and space. I read this book in the early 1980s, and it was the first novel I saw that vividly depicted the whole process of human beings from birth to extinction (or sublimation) in a brisk few pages, in which the charm of science fiction was fully expressed, and the God-eye-view me a suffocating shock. At the same time, *2001* showed me a completely different kind of writing, with both philosophical abstract transcendence and literary subtlety, to depict the immensity of existence in the universe that we can't grasp in our perception or imagination.

Clarke's *Rendezvous with Rama*, on the other hand, exemplifies science fiction's ability to create imaginary worlds; the entire work reads like a Creator's grandiose design documents for an imagined alien world in which every brick is exquisitely laid. As with 2001, the aliens never appear, but the imagined world itself is already mesmerizing, and if Verne's novels made me fall in love with sci-fi, Clarke's work was the initial impetus for writing sci-fi.

The three Dystopia novels: Orwell's 1984, Huxley's A Beautiful New World, and Zamyatin's We are only categorized as the fringes of sci-fi, but I saw in them sci-fi literature ability to reflect and intervene in reality from perspectives that are not possible in traditional realist literature. *1984* does not have a very high status in the literary world, its influence is mainly in the political and sociological fields, in the just concluded Chengdu Science Fiction Convention, even some writers believe that it *1984* thar prevented 1984 from becoming *1984*, which is of course a bit overstated, but in addition to bringing the enjoyment of the imagination, sci-fi literature also has special powers beyond other genres of literature. In my discussion with Prof. Jiang Xiaoyuan, we both admitted that among the dystopia trilogy, 1984, which seems to be the darkest, is in fact the brightest, in which human nature, though repressed, at least exists; whereas in the other two worlds, human nature has already been disappeared by technology. This is a special kind of darkness impossible in realist literature.

From a literary point of view, Tolstoy's War and Peace is not in the same class as Herman Wouk's The Winds of War series, but what I am concerned about is the bird's-eye view of the whole situation that they share; they are both novels depicting human wars in a panoramic manner, and compared with those novels about personal feelings that are like an exquisitely sculpted grain of rice, such a magnum opus can make people appreciate the whole of mankind as a racial existence, which also happens to be the perspective of science fiction literature.

Asimov's *The Intelligent Man's Guide to Science* is a long listicle, but it's true that I haven't seen any other popular science work with such a systematic introduction to modern science either. Carl Sagan's *Cosmos* and *The Dragons of Eden* are also early entries in the Western popsci canon, and while it now seems a bit outdated in terms of theoretical novelty, it introduced an aesthetic perspective into its description of science, which is unsurprising today but really opened up a third eye for me to look at science in the early 1980s.

The great thing about Dawkins's *The Selfish Gene* is that it's cold, colder than mere cool-headedness, and unmovingly reveals the nature of life. While such conclusions aren't always correct, they tell us about the possibility that the ultimate purpose of life and living and the world and civilization may be something we don't even think about. Singer's *Animal Liberation*, on the other hand, spreads equality and love to all beings beyond the human race, and similarly makes us look at human civilization from a height that we have not before. In any case, both books are "science fiction".

But the most sci-fi are *The First Three Minutes* by Steven Weinberg and *The Last Three Minutes* by Paul Davies, in which the authors describe in poetic terms the extremes of the universe's nascent and dying moments, when the world is so far away from reality that it might as well be real. Taking us to places we can never get to in times we can't experience is the great fascination of science and science fiction, and it has to be admitted that in this respect science does it better. All the peoples of the world have constructed their own creation myths with the boldest and most splendid fantasies, but none of them is as magnificent and mind-blowing as the Big Bang theory of modern cosmology; the long story of the evolution of life, with its twists and turns and romance, compared with which the story of the creation of human beings by God and Nüwa is really bland and boring. Then there is the poetic view of space and time in general relativity, the elf-like microcosm in quantum physics, the world created by these sciences is not only beyond our imagination, but also beyond what we could possibly imagine. Such imaginings are absolutely beyond the power of human myth writers to create. But the imagination and the beauty of science is imprisoned in cold equations, and it takes a great effort for the common man to catch a glimpse of her. Once the beauty of science is shown in front of people, its power to shock and purify the soul is enormous, and some aspects of the beauty of traditional literature are hard to reach. Science fiction is a bridge to the beauty of science, which releases this beauty from the formula and shows it to the public in the form of literature. 

## Seeing a drop of water in a sea -- reflections on traditional literary elements in sci-fi novels (2003)

从大海见一滴水——对科幻小说中某些传统文学要素的反思, posted in 2003-10-01 at the Tsinghua University BBS, Sci-Fi section.

My translation took some paragraphs from [Liu Cixin -- Beyond Narcissism: What Science Fiction Can Offer Literature](https://www.depauw.edu/sfs/backissues/119/Liu%20Cixin.html), because Liu Cixin reused some paragraphs for that.

Imagine, for example, that Tolstoy had provided the following description in _War and Peace_ (1869):

> Napoleon led a French army of six-hundred thousand men to invade Russia, gradually penetrating into its vast lands and soon coming to occupy the deserted city of Moscow. After waiting for a surrender that did not come, Napoleon ordered his army to retreat, but as the harsh cold of the Russian winter came upon them, a large part of the withdrawing French army froze to death or died of starvation. When Napoleon finally returned to France, he brought with him less than thirty thousand men.

In fact, there are many passages like this in Tolstoy's monumental work, yet he separated descriptions of this kind from the main body of the novel, confining them to their own independent sections. He was not alone in this. Herman Wouk also attached historical accounts of World War II to the main body of his novel, _The Winds of War_ (1971), as stand-alone appendages. Summed up as "Global Waterloo" and read on their own, they could make a good popular history of the Second World War. Both Tolsoy and Wouk, separated by a century, chose simply and directly to tell their readers: these are historical events, they are not an organic element of my work and not truly part of my literary creation. Indeed, macro-descriptions of historical events cannot form the main body of a mainstream literary work, for then the novel ceases being fiction and becomes a work of history. There are, of course, many novels that unfold against a historical panorama, including both Yao Xueyin's epic _Li Zicheng_ (5 volumes, published 1963--1999) and Howard Fast's _Spartacus_(1951), but the main body of these works is made up of the detailed description of historical figures, reflecting the larger picture of history with a multitude of details. Even these works cannot use macro-descriptions of historical processes to form the main body of their text; that is the work of historians, not novelists.

But science fiction is different, behold the following text:

> Sirius Commander Noelopan led a massive fleet of 600,000 starships on an expedition into the solar system. Humans retreated, taking all available energy from the planets before retreating into outer space and prematurely transforming the sun into a red giant from which it was impossible to extract any energy. The Sirian Expeditionary Force penetrated deeper into the solar system and eventually captured Earth, which had become a desolate planet. After a long wait for peace that failed, Noelopan had to order the army to retreat. The harsh black hole flood period of the first spiral arm of the Milky Way arrived, and on the way back, due to energy depletion and loss of maneuverability, a large number of starships were swallowed up by floating black holes, and Noelopan  finally returned to the Sirius system with less than 30,000 starships left in the fleet.

This is also a macroscopic depiction of history, and unlike that earlier passage, it is also fiction, a literary creation of the author, because it is history created by the author, and both Noelopan and his Starfleet come from his imaginary world.
This is the main difference between science fiction literature as opposed to mainstream literature. Mainstream literature depicts worlds that God has already created. Science fiction literature, on the other hand, creates the world as God did and then depicts it.
Because of this difference, we must reflect on certain elements of mainstream literature in science fiction, taking the perspective of science fiction literature itself.

### 1. Details

Novels must have details, but in science fiction literature, the concept of details has changed dramatically. There is such a science fiction story *Singularity Fireworks*, in which describes a group of super-consciousnesses for whom Big Bang-esque explosions are nothing more than an amusing evening of fireworks. And, in fact, every explosion is a Big Bang that gives birth to a universe. The following describes our universe being born this way:

> "What a good one! What a good one!" Entity One exclaimed as the firework exploded in emptiness.
> 
> "A least better than the last few," Entity Two agreed nonchalantly. "The laws of its physics forming after its expansion are equally distributed and the elementary particles percolating from its pure energy look good as well."
> 
> The firework's explosion vanished as its ashes slowly descended.
> 
> "Wait a minute! Something more is happening there!" Entity One called out, just as Entity Two was about to light another singularity firework. Handing Entity Two a telescope it continued, "Look in the dust, the cooling matter is forming many tiny, low-entropy aggregations that seem interesting."
> 
> "Huh," Entity Two raised the telescope. "They can reproduce themselves and microscopic consciousnesses are emerging." It paused, "Wait, wait, some of them have even managed to infer that they have come from an exploding firework, how fascinating ...

There can be little doubt that the above passage provides details. It describes the dialogue and perspectives of two entities watching fireworks. These details are, however, very unusual in that they hardly describe the small things. Mainstream literature often cannot describe the protagonists' first kiss in less than two hundred words; here, however, that length is sufficient to describe the entirety of the universe's 15-billion-year history, starting with the Big Bang and covering the entire history of life and civilization. It goes even further, unfolding a vision of a supra-cosmos beyond our universe. In contrast to the "micro-details" of mainstream literature, these are "macro-details" that only a sci-fi story could provide.

The same content would be depicted in mainstream literature:

> The universe was born in the Big Bang and later formed stars including the Sun, and later the Earth was formed next to the Sun. More than a billion years after the emergence of the Earth, life appeared on its surface, and later life emerged as human beings after a long evolution. Humans went through the primitive age, the agricultural age, the industrial age, and entered the information age, began to think about the origin of the universe, and proved that it was born in the Big Bang.

Is this a "detail"? Obviously not. That's why macro-details can only be found in science fiction.

In fact, such details are very common in science fiction. The best example is in "2001: A Space Odyssey", in the last chapter where the astronaut is transformed into a purely energetic state. In these details, science fiction writers, with a flick of the pen, move across a billion years of time and ten billion light-years of space, turning the world and history encompassed by mainstream literature into an insignificant speck of dust in the universe.

In the early days of science fiction, macro-details were not common, and it only appeared in abundance when science fiction literature extended its tentacles into the depths of the universe, while at the same time beginning its contemplation of the origin of the universe. It is a sign of the maturity of science fiction, and it is also an expressive style that best reflects the characteristics and advantages of science fiction.

Here there is no intention at all to disparage the micro-detailing of traditional literature. It is also an essential factor in science fiction, and a science fiction novel without vivid micro-detail is like a giant with one leg missing. Even if all science fiction is composed of micro-details, there is no lack of classics such as *Light of Other Days* (Bob Shaw, 1966).
Now the pity is that, while emphasizing micro-detail, macro-detail is not recognized among critics and readers of domestic science fiction, and people generally have two reactions: it is hollow; it is just a long synopsis.

Clarke's *The Star* (1955) is a classic among science fiction short stories, and its final line, "What was the need to give these people to the fire, that the symbol of their passing might shine above Bethlehem?" It is a timeless line of science fiction, and an example of macro-detail. But it would certainly not have been published if it had been written in this country, for one simple reason: it has no details. If we say that "2001: A Space Odyssey", though covering a vast region of space and time, has written all that can be said, allowing no further expansion, then "The Star" is really like a synopsis of a full-length novel. If you hand this synopsis to an old editor of a domestic publisher who is looking for sci-fi novels, he or she may still think it's too sketchy. In China, there are also a lot of very good works that can't be published on the grounds of "lack of details", the most typical example being Feng Zhigang's *Planting Civilizations* (种植文明 by 冯志刚). At the symposium after the 2001 Galaxy Awards, a woman sternly accused, "The lack of seriousness in sci-fi creation has gotten to such a point that some people have taken the synopsis of a novel and passed it off as a masterpiece!" Seeing Feng's bitter smile next to me, I was tempted to explain a few words, but looking at her righteous indignation, the words were scared back into my stomach. In fact, this piece is still much more detailed than some foreign classics. If you don't believe me, you can take a look at *The Gravity Mine* by Stephen Baxter, which was shortlisted for the Hugo Award in 2001. Calvino's *The Spiral*, and then *The First and the Last Man* by Olaf Stapledon from the ancient time of 1930. I've heard that Feng is expanding his "synopsis" into a full-length book, which is actually a common practice among Western sci-fi writers, but it really makes you think to note that many of the expanded full-length books are not as important to the history of sci-fi as their "synopses".

The emergence of macro-detail has a profound effect on the structure of science fiction. This reminds us of the study of software engineering (especially MIS software). According to Western theories, the development of software should be from the top down, that is, first build the overall framework of the software, and then gradually refined. In China, due to the limited developmental level of management and IT science, the development of enterprise MIS software is basically the opposite, that is, first they develop the specialized modules, and then they are gradually put together into a large system (which has resulted in many disastrous consequences). The former is very much like the macro-detail-oriented science fiction, which first builds a world according to the laws of its own creation, and then goes on to further enrich and refine it; and the latter, surely, is the construction mode of traditional literature. Traditional literature has no way to write from the top down, because the structure above has already been built, and describing it is not a literary matter.

Science fiction is precipitously expanding the descriptive space occupied by literature, giving us the potential more vividly and profoundly to show Earth and humanity from the vantage point of the entire universe. It can also show the several thousand years that make up the traditional world of literature in a new light: watching Romeo beneath Juliet's window is certainly more interesting when viewed from a telescope in the Perseus Cloud than from a nearby bush.

Science fiction can make us see a drop of water from the ocean.

### 2. Characters

The social history of mankind is a history of the rise of the status of man. From Spartacus rushing out of the gladiatorial arena brandishing his sword to the revolutionaries in France shouting "liberté, égalité, fraternité", man has been transformed from a means to an end.

But in science, the status of man is evolving in the opposite direction, from being God's creature (everything else in the universe is furniture given to us by this old man), and the master of all things, to being degraded to being essentially indistinguishable from other animals, and then to being degraded to an insignificant bacterium on a grain of sand in a certain corner of the universe.
Science fiction belongs to a literature that is inextricably linked to society and culture, but it was spawned by science, and the question now is, in which way do we lean concerning the status of man?

Mainstream literature has undoubtedly leaned to the former. "Literature is a human study" has become a nearly axiomatic creed, and a novel without characters is unacceptable.

Looking at the not-so-long history of world science fiction, science fiction has not abandoned characters, but how it uses and treats characters have been greatly diminished compared to mainstream literature. By far, those works of science fiction that have become classics have not been successful thanks to their characters. Of all the movies we've ever seen, the most flat and stilted characterization was created by 2001: A Space Odyssey, in which scientists and astronauts stares blankly and drones on machine-like at a constant syllable-per-second. Even if the lacking of characters in other sci-fi works is due to the writer's disinterest or inability, the movie of *2001: A Space Odyssey* can only a deliberate choice by director Kubrick. It's as if he's telling us that people are just symbols in this work. He does this so successfully that after seeing the movie, it is hard to distinguish the only two astronauts in the spaceship, who seem to have no personality traits other than their names.

Character status changes in science fiction as much as detail, again because science fiction dramatically expands the space available for textual description. Another important reason is that science fiction's natural connection to science makes it possible to have a cold, hard view of humanity's place in the universe.

The concept of characters has been expanded in science fiction in two main ways:

One is the replacement of the image of the individual by the image of the race as a whole. Unlike traditional literature, science fiction has the possibility of depicting multiple civilizations other than human beings and assigning different images and personalities to these civilizations and the races that created it. The races that created these civilizations could be aliens or different groups of humans that went into outer space. The aforementioned *Planting Civilizations* is a prime example of the latter. We call this new literary image the racial image.

Second, a world appears as an image. These worlds can be different planets and galaxies, or different branches of parallel worlds, and in recent years, many depicted virtual worlds running in computer memory. This is subdivided into two cases: one is that these worlds are populated (with people of whatever kind), and this world image is, in fact, a further extension of the racial image described above; the other case is that of the unpopulated worlds, which are later accessed by people (mostly explorers). In this case, science fiction is more concerned with the natural attributes of the worlds and the role it plays for the people who enter them. Such a world is often portrayed like a villain in traditional literature, because they conflict with the people who enter it. There is also a very rare type of world-image in science fiction, worlds that exist autonomously, which man never enters, and which the author depicts from a supra-conscious viewpoint, as in the case of *The Library of Babel*. These are rare and difficult to read, but they push the science fiction character to the limit.

Neither the racial image nor the world image can exist in mainstream literature, because a literary image exists on the premise that it is possible to compare it with other objects, and mainstream literature that depicts a single race (human beings) and a single world (the Earth) has to refine the granularity of the image down to the individual. Thus, the racial image and the world image are science fiction's contribution to literature.

These two new images have apparently not been recognized by domestic readers and critics. Our comments on science fiction novels still continue the with traditional literary thinking, unable to accept works not centered on traditional character images, not to mention the conscious creation of novel racial and world images, even though the creation and appreciation of these two images is the core of science fiction literature.

The lack of Chinese science fiction at the literary level is essentially the lack of these two images.

### 3. The reality and ethereality of science fiction topics

In fact, there is not much to discuss on this topic from a theoretical point of view. Sci-fi is for science. Once science is abandoned, then there is only fiction left. To show the imaginary world is the beginning and end of this genre. Depicting only reality with sci-fi is awkward like using an airplane propeller as an electric fan.

However, domestic readers favor science fiction that is close to reality, and cannot accept imagination that is even a little out-there and crazy. Under such circumstances, most of our sci-fi is near-future.

One thing has always puzzled me: why do you want to read sci-fi when you want to read depictions of reality? Isn't *People's Literature* magazine good for it? Isn't *Harvest* maganize good? Isn't the novel *Ordinary World* by by Lu Yao good? In terms of the level and depth of the depiction of reality, science fiction is naturally inferior to mainstream literature.

Many years ago, I saw a Soviet comedy movie, in which there was this scene: a large passenger plane landed on the highway and drove with the car, which obeyed all the traffic rules, stopping at the same red light as the car, green light.

This is a wonderful portrayal of the current state of the domestic science fiction. Science fiction is a genre that can fly up, but we prefer to let it crawl on the ground.

### 4. Heroism in Science Fiction

Modern mainstream literature has entered the era of mocking heroes, as in that famous contemporary saying that the sun is a piece of shit and the moon is a piece of ass-wiping paper.

In fact, this approach is not entirely without merit. If you think about it scientifically and rationally, heroism is not a positive word. "Was the behavior of those German tank drivers and Japanese kamikaze pilots in World War II heroic? Of course, it can be argued that it was not, because they were fighting for an unjust side. But on further reflection, this argument brings us nothing but confusion. Ordinary people can become heroes without being an ethicist, and it is impossible for them to judge the justice or injustice of the cause they are engaged in. More importantly, even for ethicists, judging a war from a moral perspective is difficult. Whether a war is just or not is more a matter of your feet than your brain, i.e., which side you are on. Wars such as World War II, where there is a basic consensus on their moral nature, are extremely rare in human history. According to the traditional notion of heroism, when a war comes, if ordinary people want to do their duty, whether their behavior is heroic or not depends on the luck of the draw. Worse, the probability of hitting that luck is not even one-half of a coin toss. Over time, people must have come to believe that the fallen soldiers on both sides in most wars are meaningless cannon fodder. Looking at heroism again with this definition, one realizes that it has brought far more disaster than progress to mankind throughout history. Nor did the heroine of my story, *The Glory and the Dream*, die for a just cause. In that case, are all those tragic sacrifices at the cost of life, all those magnificent, earth-shattering feats that only human beings can perform, all meaningless, perverted farces?

A more sensible and fair approach would be to distinguish heroism and morality, and to treat it only as a uniquely human quality, an important marker of distinction between human beings and other animals.

As civilization advances, and as the concepts of democracy and human rights are recognized throughout the world, heroism is fading. By mocking heroes, literature is calling for humanism from another angle, and in a way it is historical progress. It is conceivable that if human society develops along its current trajectory, heroism will eventually become something alien.

The question now is: will human society certainly develop along its current trajectory?

Humans are fortunate that since the advent of civilization, the human world as a whole has never faced a sudden extinction event from the outside. But that does not mean that such a catastrophe eludes us in the future.

When the Earth faces a full-scale invasion by an alien civilization, and in order to defend our civilization, one billion people may need to become cannon fodder under the lasers of the aliens; or when the solar system sails into a cloud of interstellar dust, and the deteriorating Earth's ecology necessitates the deaths of three billion people in order to avoid the deaths of six billion people all together, will our literature continue to ridicule heroism in such a scenario? Will shouting "humanity" and "human rights" save humanity then?

Looking at mankind from the perspective of science fiction, our race is extremely fragile. In this cold universe, mankind must bravely sacrifice a part of it in exchange for the continuation of the whole civilization, and this calls for heroism. Now that human civilization is in an unprecedented stage of smooth development, it is true that heroism is less important, but that does not mean that it will still be unimportant in the future contemplated by science fiction.

Science fiction literature is the last place for heroism and idealism, so let them dwell here for a while longer.

### 5. A third image in science fiction

Having previously mentioned the two images that characterize science fiction literature -- the racial image and the world image -- it also has a third image that is not found in mainstream literature: the image of science. Since science fiction is a direct product of scientific development, science always exists in it either explicitly or implicitly, whether it is traditional hard science fiction or later soft science fiction. It fills the space between lines as a lifeblood, and as a ubiquitous image, it has been always depicted by science fiction.

Chinese science fiction has been learning from mainstream literature, but it has not been a good student: we pay close attention to characterization and stylistic sophistication, and as a result, our works seem to be nothing more than essays by elementary school students. We pay close attention to reality, but compared with the traditional novelists, it is still just the pretending-to-be-sick moaning of a group of inexperienced students. We have dabbled with postmodern, ismand the result is a total mess. But in one thing, science fiction is better than mainstream literature, that is, the scandalization and demonization of science.

In fact, up to now, the mainstream literature just keeps a certain distance from science and does not hurt it, this is because on the one hand, the pastoral setting of traditional literature has little relation with science; on the other hand, to scandalize science, one needs to understand it, and at this point, the mainstream literature may meet an obstacle. Science fiction, however, has a natural advantage in this regard, and does so with relentless effort!

I think we all know very well what has become of the image of science in our science fiction.

It's true that Western science fiction writers have done a better job of this than we ever have, but that's no reason for us to do so. Science is quite popular in Western societies, and rethinking its consequences may be healthy. But even so, this tendency by the sci-fi criticism community has been unanimously condemned by the Western scientific community. In China, science is still a small candle flame in the wilderness among the general public, and a breeze can blow it out. The first task now is not to predict the disaster of science; the real disaster facing Chinese society would be the loss of the spirit of science among the masses.

The power of science lies in the public's understanding of it. This is the truth. To let the spirit of science take root among the public is a great cause, compared to which [the other purposes of] science fiction seems trivial. Originally, there is no contradiction between the two, and the old generation of Chinese science fiction writers were full of hope that sci-fi would become a part of this great cause, but now it seems that this is a very naive hope. But at least, sci-fi should not cause damage to this cause. Science is the mother of sci-fi, do we really want to be her enemy?

If we can't attract readers without portraying science in a negative light, without making it gruesome and horrible, then let's stop the pen in our hands. It's not a big deal, there are many other interesting things to do. If Chinese science fiction really disappears, as a faithful old science fiction fan, I sincerely pray that it will die a decent death.

### 6. Shackles of stereotypes

I have written some comparisons between sci-fi and mainstream literature, and I do not mean to belittle mainstream literature at all. The above mentioned advantages of science fiction are determined by its own nature, and it is not therefore higher than mainstream literature in skill -- on the contrary, now it does not make good use of its advantages. In fact, when compared with mainstream literature, we often feel inferior, when seeing their courage to explore and innovate the methods of literary expression. From stream-of-consciousness to post-modern literature, a dazzling variety of expressive methods have been developed with the spirit of "I do what I want". If we look at science fiction, we have not created our own expressive techniques. The New Wave movement was just an effort to take the techniques of mainstream literature and use them for ourselves, but later found that they were not suitable, and the whole movement has been called by researchers of science fiction theories as "an effort to yield up the value and status of science fiction to mainstream literature". As for the aforementioned macro-details, racial image, and world image, they are all unconscious creations of science fiction writers, which have not risen to the height of theory, let alone a self-conscious expressive technique. In foreign countries, these techniques are not even acceptable.

In fact, some traditional literary elements extended or subverted in sci-fi, such as characterization and detailing, are undergoing drastic changes in mainstream literature too. Mainstream literary figures like Borges and Calvino have long abandoned those traditional dogmas and achieved great success.

On the contrary, the domestic science fiction critics are religiously picking up the broken yoke that others have thrown away, solemnly putting it on themselves, screwing the top bolt to the tightest, and lashing out at those science fiction works that have even slightly crossed the threshold, as if they have become the guardians of the dignity of literature. Look at those online reviews, full of stereotypical dogma, without a little bit of young people's sensitivity and vigor, sometimes I really want to ask: "Venerable one, how many centuries have you lived?".

Innovation is the life of literature, but also the life of science fiction. In the face of this literature from the sea to see a drop of water, we must first have the sea's bosom!

## Why is humanity still worth saving? -- debate between Liu Cixin and Jiang Xiaoyuan (2007) {#liu-jiang-debate-2007}

Originally published in *New Discoveries* magazine, Issue 11, 2007

Host and scribe: Wang Yan

Where will the human race be taken to in the end? Can humanity's belief in the future be sustained? With what? Science? What can science solve? What can't it solve?

On August 26th, 2007, at the "White Night" bar run by poet Zhai Yongming, the editorial board of New Discoveries invited two guests to Chengdu to attend the "2007 China (Chengdu) International Science Fiction and Fantasy Convention". The editorial board of New Discoveries invited two guests to Chengdu to participate in the "2007 China (Chengdu) International Science Fiction and Fantasy Conference": Liu Cixin, a famous sci-fi writer, and Jiang Xiaoyuan, a professor at Shanghai Jiaotong University who has been frequently publishing sci-fi commentaries in recent years, to have a fascinating conversation about our common doubts, and a face-to-face exchange of ideas on sci-fi, scientism, and the relationship between science and humanities, and other issues. The following is the record of the conversation.

**Liu:** Historically, the first science fiction novel, Mary Shelley's Frankenstein, was anti-science, and her portrayal of science was not very bright. And even earlier, Gulliver's Travels, there is a chapter about scientists [on Balnibarbi], and they are described in a very comical way. You can see a science degenerating into an academic formality. But Jules Verne suddenly became optimistic because he was inspired by the rapid development of science and technology in the late 19th century.

**Jiang:** A lot of things from the West were brought in, and they were selected, and Verne fit our need for propaganda and education. His early optimism is inseparable from the development of science and technology in the 19th century, when people did not yet see science as a monster, but he became pessimistic in his later years.

**Liu:** Verne did write some very complex works, with a lot of complex human nature and plots. One is about a ship on which many people form a society. Also his *Facing the Flag* has an anti-science element, depicting that science can bring about some disasters. Then there's *The Begum's Millions*. But these do not dominate, and almost all of his still-read works are more ideologically innocent. It's worth noting that the later Golden Age of science fiction came during the Great Depression, in the 1920s. Why? Probably because people wanted to take comfort in the illusions created by science fiction and escape from reality.

**Jiang:** It's said that book publishing was booming at that time. There's a little story about Verne, he wrote about the Xujiahui Observatory [L'Observatoire de Zi-Ka-Wei] in *Robur the Conqueror*. He said there was a flying machine, and the director of the Xujiahui Observatory thought it was sent by intelligent beings from other planets, similar to what we call UFOs today, but the directors of the observatories in other countries didn't believe him because he was Chinese, but later on, it turned out to be really from an extraterrestrial civilization. This story made a mistake: the director of the Xujiahui Observatory at that time was not Chinese, but a Frenchman, a compatriot of Verne.

**Liu:** Verne created the image of the big machine in his novels, which has been used in many anti-science works since. Forster wrote a very famous anti-science science fiction work called *The Machine Stops*. The story is that the whole society is a big running machine, and people don't even walk anymore, they live underground. One day the machine breaks down and civilization is destroyed.

**Jiang:** Many readers have noticed an evolution from optimism to pessimism in your work. Is this similar to the pessimism of Verne in his later years? Is there also some ideological change behind it?

**Liu:** The connection is not very strong. Whether it's pessimism or optimism, it's actually a need for expression. In the past few years of writing sci-fi, I haven't had any ideological shifts. I'm a fanatic of Technologism, and I personally believe that technology can solve all problems.

**Jiang:** That is actually Scientism.

**Liu:** Some people say that science can't solve all problems, because science may cause some problems, such as the corruption of human nature, degeneration of morality, or even as Nancy Kress said, "Science makes humans inhumans.". But what we have to be aware of is that human nature is actually changing all the time. We and Stone Age people would think of each other as the inhuman. So the change should not be rejected or feared, we are definitely changing. If technology reaches that point, I can't think of any problem that technology can't solve. I think that people who think that science can't solve the problems we face are doing so because they have a concern that the human itself should remain uncorrupted.

**Jiang:** The argument against scientism, that science may corrupt the human, is only one aspect of it, and the other aspect is that science really can't solve some problems, and some problems can never be solved, such as the purpose of life.

**Liu:** What you say does hold true, but I'm not talking about issues that are that broad. And I think the purpose of life can be solved by science.

**Jiang:** Can we rely on science to find the purpose of life?

**Liu:** But science can stop me from searching for the purpose of life. For example, we can use science to eliminate the desire to find the ultimate purpose from our brain.

**Jiang:** I think a lot of scientific and technological developments are, on the positive side, neutral, depending on who uses them: bad people use them for bad things, good people use them for good things. But there are other things that are fundamentally bad. What you've just described is a very dangerous and even evil thing, and no matter who uses it, it's evil. If we go ahead and develop something like that, it is evil. Why has the West promoted anti-scientism over the years? Against scientism, not against science itself. Scientism is very ugly in the eyes of many Westerners.

**Liu:** What I want to point out is this: Is there truly a difference between convincing you with words, and influencing your essential judgment by putting a chip in your head?

**Jiang:** Of course there is a difference. By convincing me, you honor my free will.

**Liu:** Now I'm going to ask this question, which I'm going to write about in my next work: if you build such a machine, but it doesn't directly control your thoughts, and you take whatever thoughts you want, is this acceptable? [This is the "mental seal" in *The Dark Forest*]

**Jiang:** This is acceptable, but the person who goes to get the thoughts should be wary of it.

**Liu:** Right, that's what I was going to say. According to your point of view, in the Dystopia Trilogy, 1984 is the brightest, in which human nature is only repressed, while in the other two, human nature disappears. If you were given the choice of 1984 or Brave New World, which would you choose?

**Jiang:** Probably more people would choose to go to Brave New World. The premise is that you only have two choices. But what if there are other options?

**Liu:** One of the things I remember you talking to me about is that mankind is not philosophically ready for total extinction. Now let's link science and technology, which is a tool for alienating people, to the existential catastrophe. If this cataclysm were to come, wouldn't you have to use this tool?

**Jiang:** Look at it this way - if we are to prepare for the cataclysm today, then I think there are two most important things. The first is for us to gain interstellar navigational capability, and that capability is not merely in launching an occasional spaceship, but migrating on a large scale. The second is for us to find a new homeworld.

**Liu:** That's great. But what if the disaster is imminent, say next May, what do we do now?

**Jiang:** Do you think that using technology to control people's minds can cope with this disaster?

**Liu:** It by itself can't avoid the disaster, but it can organize human beings in a way that transcends moral boundaries and preserves the whole at the expense of the parts. Because right now human morality can't handle the kind of dilemma in *The Cold Equations*: one person dies, or two people die together?

**Jiang:** If you want me to accept mind-control technology (microchips in the head) on the grounds of preventing a future catastrophe, that's a catastrophe in itself, and one can't accept an catastrophe now just because one expects another in the future. The day of that disaster is still unknown, and it may or may not come. In fact, similar confusions have been discussed in several Western works, and ultimately they all denounce this as evil. Like in *Digital Fotress*, where everyone's e-mail is monitored, it's said that it's for the purpose of counter-terrorism, but in fact it's already a form of terrorism.

**Liu:** I'm just giving an example to illustrate a point: whether technology is evil or not, and whether its role in human society is evil or not, depends on what the ultimate purpose of human society is. Mr. Jiang believes that controlling the mind is evil because it takes away humanity. But if the ultimate purpose of human beings is not to sustain their humanity, but to survive, then it is not evil.

**Jiang:** This involves a value judgment: is it important to survive or sustain humanity? It's as if there are two paths ahead: one is to lose humanity but still survive, and the other is to sustain humanity until the final moment and then perish. I believe that not only me, but also many people will choose the latter. Because the loss of humanity is the same as extinction of Humanity.

**Liu:** In fact, from the beginning of writing sci-fi until now, I have been thinking about this question: which one is more reasonable to choose?

**Jiang:** At this time I think we must respect free will and everyone must vote. People like me can vote the not-surviving option.

**Liu:** You're right about all of this, but what I want to emphasize now is a question of scale. What sci-fi does is that it can be seen on a scale that we don't normally see. Conventional moral judgments can't do the job of judging humanity as a whole. I've been thinking in terms of sci-fi, and saw that the traditional moral bottom line is deeply questionable. I can't say it's wrong, but at least it's dangerous. The concept of human nature is truly vague. Do you really think that an unchanging human nature exists from primitive times to the present? What is the one thing about human nature that has remained unchanged throughout the ages? I can't find any.

**Jiang:** I think free will is part of what is unchanging. I have always believed that science cannot deprive people of their free will. There was an incident in the United States where the local government followed the advice of an expert to [fluoridate the drinking water](https://en.wikipedia.org/wiki/Water_fluoridation_controversy) to prevent dental disease, which caused a lot of objections, the most extreme of which was: I know it's good for me, but I should still have the freedom not to want these benefits, right?

**Liu:** That's the theme of *A Clockwork Orange*.

**Jiang:** We can agree to disagree that I think it's always bad to use technology to control ideas, while you think it's good in some cases.Western science fiction is now the product of an anti-scientific ideology, a shift that has been underway since at least the New Wave Sci-fi. Anti-scientism was part of the four main demands of the New Wave movement, such as the third demand to be able to consider the darker parts of science in the future.

**Liu:** In fact, anti-scientism was already quite prevalent in the middle of the Golden Age.

**Jiang:** In the West, the mission of the New Wave has been accomplished. Do you think the mission of the New Wave in China has been accomplished?

**Liu:** Actually, there was a debate in the 1980s about whether science fiction should live under the roof of "science" or "literature", and in the end the latter won. This can be said to be a belated victory of the New Wave in China. At present, most Chinese science fiction writers are pessimistic about science and skeptical about the development of science and technology, which is a proof that they are influenced by Western thinking. In my opinion, Western science has developed to such a point that it's time to limit its power, but Chinese scientific thought has just been born, and I don't think it's appropriate to demonize it yet.

**Jiang:** I have a different view. Between the development of science and scientism, it is not the case that scientism promotes the development of science, as like how the Chinese economic policy starts by development at the expense of pollution, and then fix the pollution after development is done. Scientism actually harms science from the beginning.

**Liu:** But we are talking about the attitude towards science in science fiction, introducing its positive effects and promoting scientific ideas, which is not a mistake, right?

**Jiang:** In fact, in China, the authority of science is already too big.

**Liu:** The authority of science in China is great, but the spirit of science in China is not.

**Jiang:** We are moderately limiting the authority of science, and doing so is not the same as destroying the spirit of science. The spirit of science does not include the unlimited worship of science itself -- the spirit of science includes the spirit of skepticism, which means it is possible to be skeptical of science itself.

**Liu:** But there needs to be a ratio between skepticism of science and affirmation of science. How can all science fiction works be 98% anti-science? That's not reasonable. If, in the eyes of the people, scientific development brings about a dark world, always evil, always catastrophic, always irrational, then how can the spirit of science be promoted?

**Jiang:** I used to think this was problematic, but now I am more inclined to accept it. Let's say, for example, that a small child gets good grades and is very proud of them. It's not unreasonable for an adult to stop praising him for every high score and start only criticizing his shortcomings.

**Liu:** Can you tell us in what ways the authority of science is expressed in China?

**Jiang:** In China, many people believe that science can solve all problems, and in addition, they believe that science is the best system of knowledge, above all other systems of knowledge.

**Liu:** This is where I really differ from you. Although I don't think that science is superior to other systems, I do think that it is the most complete system of knowledge that we have at the moment. Because it recognizes logical reasoning, it requires objective and experimental verification and does not recognize authority.

**Jiang:** As a student of astrophysics, I used to believe in this completely, but I have had a change of heart since about 2000, and of course this change has developed slowly. The reason was that I was exposed to some Western anti-scientific works and I felt that there was really something to it. You believe that science is the best system, so you assume that everyone needs to be scientific. But I think it's fine as long as a portion of the population is scientifically minded.

**Liu:** It should at least be mainstream.

**Jiang:** It's not that only scientifically minded people can make the right choices; in fact, the opposite may be true in many cases. Let's take an example to illustrate this.

Let's take for example the Steven Soderbergh's version of *Solaris*, where some people are on a space station and encounter a lot of strange things, and the hero, Chris, meets his wife, Rheya, who is long dead. There is a Dr. Gordon, who says to Chris, "Rheya is not human, so kill (every one of) her." Dr. Gordon's judgment is perfectly in keeping with the spirit of science and materialism. In the end they are faced with a choice: either go back to Earth or be sucked into the depths of the ocean. Chris decides at the last minute not to go back to Earth, preferring instead to shout Rheya's name and let the ocean suck him down. Here, he is lacking in scientific spirit and is only doing it for love. Of course, Soderbergh lets him jump off the ocean and goes back to his house, where Rheya is waiting for him. Isn't this choice, made not out of the spirit of science, even better? So Soderbergh says that the planet of Solaris is actually a metaphor for God.

**Liu:** Your example does not show that decisions made by scientism are wrong. There is a question of scale. The hero is only making this choice on an individual rather than a human scale. Think about it the other way around, what would be the consequences if we followed your choice and brought her back to Earth? This thing that is not human, you don't know what her nature is, or how much energy she has, or what she will bring to Earth?

**Jiang:** It's good to have love. There are things in the human world that are above the spirit of science. I want to make it clear that there are not necessarily other systems of knowledge that are better than science, but there can be many other systems of knowledge that should be on an equal footing with science.

**Liu:** Science is the system of knowledge that mankind can rely on the most. I recognize that for spiritual needs, religion does have a better approach, but the existence of science is necessary for our survival. There may be a more rational system of knowledge in the universe, but until there is, why can't we trust science?

**Jiang:** I'm not saying I don't believe in science, only that we have to be tolerant of other people's unbelief in science. When faced with a problem that can be solved by science, I will use science to solve it, but when science cannot solve it, I will use something else.

**Liu:** The consequences of this disbelief don't seem to be very serious in a time of peace, but not so in a time of extremity. It seems that our discussion has to end up on the ultimate purpose whichever way we go. One can simplify the world picture and do a thought experiment. Suppose you, me and her [the host] are all that's left of the human world, and the three of us carry everything of human civilization. And we have to eat her to survive, do you?

**Jiang:** No, I won't.

**Liu:** But the entire civilization of the universe is concentrated in our hands, Shakespeare, Einstein, Goethe ...... If we do not eat, all the past civilization will be completely annihilated with your irresponsible move. You know the universe is very cold. If we all disappear, there is only a darkness, in which there is no distinction of humanity or inhumanity. By choosing to be inhuman now, humanity will have a chance to re-emerge in the future.

**Jiang:** The question of whether to eat or not to eat is not one that science can solve. I think it is more responsible not to eat than to choose to eat. If you eat, you lose your humanity. It took a long time for human beings to evolve to this point of humanity, and I can't lose it like that. I want the three of us to fight together and see if we have a chance to survive.

**Liu:** The premise that we're assuming that either the two of us will survive or the three of us will perish together is a very powerful thought experiment. It's an ironic fact that being destroyed is like a wall across the face, and I once wrote in *The Wandering Earth*: "You are walking across a plain when you suddenly encounter a wall. The wall is infinitely tall and extends infinitely deep underground. It stretches infinitely to the left and infinitely to the right. What is it? -- Death.".

**Jiang:** It reminds me of the most profound question in *Battlestar Galactica*: "Why is humanity still worth saving?" In the scenario you just envisioned, we lose our humanity by eating her, and a humanity that has lost its humanity has cut itself off from Shakespeare, Einstein, Goethe, etc. What is left to save?

But literature may offer a better alternative. When I was very young, I read Byron's long poem *Don Juan*, which contains a similar scene: several people are stranded on a boat, and lots are cast to decide who will be eaten, but Don Juan is adamant that he won't eat. Luckily he didn't eat it, because the cannibals died of poisoning. At that time I was very touched and decided that in the future, if I encountered such a situation, I would definitely not eat anyone. I don't know whether eating people will poison me or not, but Byron's moral of the story is for us not to lose our humanity.

I would like to ask Mr. Liu a question: among Chinese science fiction writers, you can be said to be an alternative, because most of the others go for anti-scientism, but you firmly believe in the benefits and light brought by science, and yet you are considered to be the most successful, what is the reason for this?

**Liu:** It's because I show a cold but calm rationality. And this rationality is reasonable. You chose humanity, and I chose survival, and readers identified with that choice. To subvert Kant: I admire with awe the starry heavens above me, but remain untouched by the moral law within me.

**Jiang:** It's rather cold.

**Liu:** When we think of these issues in terms of science fiction, it is very cold.

## Beyond Narcissism: What Science Fiction Can Offer Literature (2009)

Source: 刘慈欣：超越自恋——科幻给文学的机会, 《山西文学》 2009年第07期 

Translated by someone else already, at <https://www.depauw.edu/sfs/backissues/119/Liu%20Cixin.html>.

## Interview with *City Pictorial* (2010)

Source: [《城市画报》采访大刘的无删节版稿子](https://www.douban.com/group/topic/17709616/?_i=52143399ZoyjXW)

Liu Cixin: I'm an engineer guy, not an artistic youth. Interview with *City Pictorial*, by Xu Xiao.

> I don't have much to say except a warning. Life reached an evolutionary milestone when it climbed onto land from the ocean, but those first fish that climbed onto land ceased to be fish. Similarly, when humans truly enter space and are freed from the Earth, they cease to be human. So, to all of you I say this: When you think about heading into outer space without looking back, think twice. The cost you must pay is far greater than you could imagine.
>
> Final statement made by Captain Neil Scott, from *Death's End*

Q: Winning the [Galaxy Award](https://en.wikipedia.org/wiki/Galaxy_Award_(China)), the highest prize for science fiction in China, for eight consecutive years is an amazing record. Indeed, it would be unimaginable for a non-sci-fi writer to win the [Mao Dun Literature Prize](https://en.wikipedia.org/wiki/Mao_Dun_Literature_Prize) for eight consecutive years. How did you achieve this "monopoly"?

A: The Galaxy Award and the Mao Dun Literary Award are very different from each other. The Galaxy Award is not a national literary award, but an amateur award organized by the *Science Fiction World* magazine, and it only evaluates short stories, plus the fact that there are very few authors in China who write sci-fi -- there are only ten to fifteen of them, and all of them are amateur authors -- so it is not difficult to win this award. I've only won the award eight years in a row, and there are others who have won it ten times in a row, such as Wang Jinkang and Xinghe. The authors and readers of *Science Fiction World* are kind of like a bus, where you get on the bus and get off the bus, and a lot of people write for a while and then stop writing. People who write science fiction don't take the award as seriously as mainstream authors do, but they do so with a playful mindset, but there's nothing wrong with that.

Q: The first decade of the new century is coming to an end, looking back, what kind of mood drove you to start writing?

A: The first time I wrote science fiction was when I was in high school, because I was a science fiction fan, and I started to write when I was looking at it. In China, sci-fi fans really appeared as a group in the 1990s. I became a sci-fi fan in the late 1970s and early 1980s, when there was no such group as "sci-fi fans" and they were very isolated from each other. Now there is a community of science fiction fans, which is of great significance to the development of science fiction literature in China.

Q: Nowadays, there are many sci-fi fans and they often comment on your works on the Internet. Do these voices have any influence on your work?

A: I will go online to read these comments, but I don't read much because I have limited time. They certainly have an effect, because I'm not someone who writes fiction for myself or for critics; the main target is still the reader. But I definitely have a bottom line that I stick to.

Q: What kind of bottom line?

A: The bottom line of science fiction. I must stay loyal to my own definition of science fiction: science itself must have a relatively large role in the science fiction I write. Worldwide, this type of science fiction is actually shrinking. For example, in the United States, science fiction now focuses more on literary techniques and modernist expression styles.

Q: If someone is ready to start reading your work, what would you recommend to such an entry-level reader?

A: With the exception of *Supernova Era*, all my other works are pretty much the same, and they all fall into the category of stories that can't stand up if you take away the sci-fi idea. *Supernova Era* is not quite the same; if it were any other random disaster where only children were left on Earth, the story would hold up. However for introductory purposes, I'd suggest checking out my short story, if you don't think it's good, you won't waste too much time.

Q: In 1950, Mr. Fermi, the famous Italian, said, "Where is everybody?".

> The universe is a dark forest. Every civilization is an armed hunter stalking through the trees like a ghost, gently pushing aside branches that block the path and trying to tread without sound. Even breathing is done with care. The hunter has to be careful, because everywhere in the forest are stealthy hunters like him. If he finds other life -- another hunter, an angel or a demon, a delicate infant or a tottering old man, a fairy or a demigod -- there's only one thing he can do: open fire and eliminate them. In this forest, hell is other people. An eternal threat that any life that exposes its own existence will be swiftly wiped out. This is the picture of cosmic civilization. It's the explanation for the Fermi Paradox. 
> 
> *The Dark Forest*

It's been said that *The Three Body Problem* trilogy is nothing but the story of a woman messing with her man, then they starting messing with each other, then both were messed by the universe, and finally the universe was messed by who knows what.

A: I really didn't pay much attention to the gender of the protagonist when I was writing. For example, if the protagonist of the third installment is female, it's because the protagonist of the second installment is male, for that simple reason.

Q: There are also people who say that The Third Body gives them a glimpse of what a Hollywood blockbuster feels like. Do you like that comment?

A: I like it. Hollywood blockbusters are commercial productions, but they're all skillfully made, and rarely do they invest hundreds of millions of dollars in a movie and then screw it up, and I've never seen a Hollywood blockbuster that I particularly despised. What I can't stand to watch is an arthouse movie, it's torture. As long as you spend a lot of money on it, I'd like to watch that movie, but I can't stand arthouse movies even if it's well-made. Plus, none of the arthouse movies have strong storylines, and the ones with strong stories aren't called arthouse movies, like *Kramer vs. Kramer* and *American Beauty*, and they're all painful for me to watch. I'm an engineering guy, I'm not a literary guy, I'm not interested in arthouse. My novels aren't high-literary either, they're unrefined by literary standards.

Q: In the first book of *The Three-Body Problem* trilogy, the Cultural Revolution is an important backdrop to the story. What was the reason for deciding to write it that way?

A: It started out as a desire to write a novel focused on the Cultural Revolution. After all, I spent my childhood and teenage years there and knew more about it. Then I realized that readers are not interested in the Cultural Revolution because they are all gen-80s and gen-90s, so I watered it down and made it the background of the story.

Q: What do you think about Mao Zedong?

A: Whether writing a novel or telling a story, this kind of person is very eye-catching, and if such a character appears in science fiction, he must be very charismatic.

Q: *The Three Body Problem* trilogy portrays three very different female protagonists: the rational Ye Wenjie, the dreamy Zhuang Yan, and the motherly Cheng Xin. Which one is your favorite?

A: None of them are the type of women I like. They are just tools to advance the plot. For example, Cheng Xin, the heroine in the third installment, is just a symbol that represents the universal values and morals of mankind. When you say people don't like the main character, it means people don't like their own selves. Cheng Xin is a very ordinary and normal person, the choices she makes at every critical moment are the choices that every normal person would make, in line with universal values and morals, but it is precisely this choice that drives mankind to extinction.

Q: According to the Dark Forest Hypothesis, survival is the first goal, and the choices Cheng Xin makes at critical moments are contrary to this axiom.

A: To make survival the primary goal is precisely the viewpoint of a Übermensch, and it is quite difficult. Ordinary people, like the Cheng Xin, must first follow their inner sense of morality. The Übermensch is the one who can have the mental strength and vigor to jump out of the limits of morality and grasp the final goal of survival at the critical moment.

Q: Dis-identification with Cheng Xin may affect the reader's sense of agency and identification with the novel. Did you worry about this?

A: I didn't write this person with the intention that readers would like her. This is not someone readers will like. She's actually selfish, but this selfishness is different from ordinary selfishness because she doesn't perceive it herself. People who follow morals are actually very selfish because they don't care about anything but morals and conscience, and Cheng Xin is exactly such a person. She would consider herself noble, consider herself unselfish, and consider her values and moral code to be universal and correct. As to what consequences following it would bring, she would only consider whether it would bring peace to her conscience. This kind of person has a spirit of sacrifice and is able to sacrifice her life for her values and moral code, but this does not change the verdict of selfishness. If someone that can perform "great loving without kindness" were to appear in the novel, they would be unselfish and work to benefit Humanity itself, because sacrificing one's conscience is the greatest sacrifice thing to do, and it is much harder than merely sacrificing one's life.

Q: Do you have a problem with *Harry Potter*? Because the fundamental premise of *Harry Potter* is saving the world with love, and you have the character of Cheng Xin destroying the world with love twice, and you were saying it without disguise.

A: People who write fantasy celebrate love, but people who write sci-fi are more rational. If you look at the world's major sci-fi classics, none of them are interested in love, just plain rationality. Moreover, the setting of *The Three Body Problem* is an existential deadlock, with a dark undertone, and honestly, in this setting, love can't save anyone. People who write sci-fi should keep their worldview in a state of uncertainty, if they are too determined to perceive everything, it's hard for them to write any novels, especially sci-fi literature, which is about human beings' confusion and exploration of the unknown. As for myself, I don't have an iron-clad view of human society; it may be this way in this set of books and that way in that set.

Q: Do you think authoritarian governance is the best way to solve the crisis of all mankind in science fiction?

A: According to the current trends in society, the current form of society is not conducive to solving the crisis. If the Humanity-wide crisis in the novel arrives, human society must be led more efficiently (and arguably more evilly) by a strong government -- or just as well, not by a government, but a coalition, or even an artificial intelligence. One thing is for sure: Humanity must make the decision to sacrifice the few to preserve the many, and the government or other leadership organization  in the novel exists to ensure that this decision is made. What *The Three Body Problem* is trying to say is that there is a contradiction between mankind's current moral system and mankind's self-preservation in a catastrophe.

Q: Outside of Cheng Xin, how would you characterize Yun Tianming?

A: He starts out as a nerd, sensitive, and unpopular, a character that definitely doesn't fit in today's society. Right now I don't know what he is doing after his brain was captured by the Trisolarians, but later I may write a book about his entry into the alien society. His kind of character, withdrawn from human society, is paradoxically suitable for entering an alien society, because he usually does not rely on human relationships to survive. In contrast, we, who are well-socialized animals, might fall apart when we enter the alien society.

Q: What you are saying is that nerds are easy to make a home on an alien planet.

A: Right. If you mix too well with human society, you might fall apart faster when you enter an alien society.

Q: There are a lot of ambiguities buried in the novel, such as Yun Tianming, such as the later encounters of the Trisolarian fleet, which are not expanded upon.

A: Readers can never understand the invisible constraint the author must face: length. You can't write as much as you want in a full-length novel; there's an agreement between the author and the publisher. The current market is usually 200,000 words for a long science fiction story, and with 360,000 words written for the third installment of The Three Body Problem, it's already 110,000 words over the limit, so where else can you go?

Q: Will that be followed by extra stories around the series?

A: It's hard to say at the moment. I do not dare to write a 4th entry for another reason, if the last part of the plot[^last-plot] is expanded to a 4th book, it will become a pure "space opera", ethereal story, and the real life of mankind does not have anything to do with this kind of science fiction is very difficult to write, and readers will also find it very painful to read.

[^last-plot]: At the end of the story, most of humanity has been destroyed except a few hanging on in a tiny bubble space. They received a universe-wide broadcast to return the bubble space back to the wide universe, so they decided to do so, and started surviving on a planet with a spaceship. It is unclear what they would be doing from then on, but probably they would simply die and not be able to restart human civilization.

Q: At that time, I heard that when *The Three Body Problem 3: Death's End* was almost finished, many people on the Internet ran to tell me about it.

A: *Death's End* is a consequence of both the readers and the writer being in a hurry. It was written in such a hurry that the readers were also rushing, and the editor was also rushing, but that was not the reason for the rush. The biggest reason is still the author's own haste. I wanted to finish writing quickly, because after all, I am an amateur author, and found an idle period. Whether I will be busy in the future, I can't say. 360,000 words, conceptualization, and writing, one year to complete, it's too hasty. If I had two more years, I could have done much better than this.

Q: When can we expect your next full-length book?

A: The three books of *The Three Body Problem* make up one whole story, so readers were waiting impatiently for each installment. Now that it's complete, I don't think people will be too anxious for the next full-length book. When I'll write it, I can't say.

> I feel like I'm writing like a tour guide, taking readers on a tour of my own imaginary worlds. I've been leading this tour for more than ten years, but I haven't even finished half of the attractions yet, not to mention those being newly developed. So there is always some anxiety in my heart. Because I know that accidents can happen at any time: floods can block our way, our bus can be hijacked by gunmen. As an old sci-fi fan, I know that this is not an idle worry. Of all the mishaps sci-fi may encounter in the country, the most worrying is social unrest. At a meeting for *Science Fiction World* readers and writers, I told my readers and friends that sci-fi is a kind of literature for years of peace. They were all unimpressed, but it's true. Only in a stable life can we be interested in and shocked by the disasters of the world and the universe. If we ourselves live in a crisis-ridden environment, science fiction will no longer arouse our interest. As a matter of fact, two of the first three ages of Chinese science fiction were interrupted by social unrest, which is the biggest killer of science fiction. [^three-periods] Now that the calm has lasted for more than twenty years, it feels like at the grassroots level of society, some kind of spring is winding up, and the last straw that broke the camel's back could come at any time. Hopefully, this is just a science fiction fan's idle worry. I hope the peace will continue, since that would be a great blessing for science fiction.
>
> [Liu Cixin's blog post on 2010-09-02 10:19:36. Posted in Sina Blog.](https://blog.sina.com.cn/s/blog_540d5e800100lfwn.html)

[^three-periods]: First period: 1950 -- 1966, interrupted by Cultural Revolution. Second period: 1976 -- 1983, interrupted by Anti-Spiritual Pollution Campaign. Third period: 1990s -- now.

Q: You have a poetic expression when describing good science fiction: "It will make you want to look up at the stars." 

Can you tell me what the starry sky in Shanxi is like for us?

A: Shanxi is a big energy province with a high density of power plants and serious air pollution ... So, starry sky ...?

Q: How about if you asked fans scattered across the country to photograph the stars in their eyes and send them to you?

A: It's basically impossible, unless with a professional digital camera. You can't get it with an ordinary camera. How about you take a picture of one? It's black.

Q: I can see that you are very rational, and you douse cold water over all artistic flames. Besides being rational, do you have a strong sense of crisis?

A: I don't have much sense of crisis in my life, I just take things as they come, and I can withstand even the biggest social waves. But I have a strong sense of crisis about sci-fi. It's my hobby, and I worry that it's going to fall into a slump. In the 1970s and 1980s, sci-fi hit a low point, and sci-fi fans of my age have experienced it, with psychological trauma and memories. Once society is in turmoil, people simply don't have the heart to interpret sci-fi, there are enough crises around, who comes to see crises in science fiction.

Q: I heard that in your college days you once traveled to the China-Vietnam border with a consolation group and witnessed the fighting, bloodshed, and death where you could see the Vietnamese army. Is that true?[^sino-vietnam]

[^sino-vietnam]: During the Sino-Vietnamese War (1979), some civilians were organized into groups and visited Chinese soldiers near the frontiers. They typically brought poems, songs and dances, food, etc, to improve the morale of the soldiers.

A: All I can say is that war is not the same thing as what we think or see on movies, but these have little impact on the novel, and I never intended to include in the novel what the real war I saw was like.

Q: What life experiences do you think you've had that kids in the big city who are well-dressed and well-fed might not be familiar with?

A: I didn't grow up in a big city, nor did I grow up in a rural area. I grew up in an industrial and mining enterprise, which happens to be at the grassroots of Chinese society that is neither up nor down. Most people in China are very ordinary people, people like me, so I don't think my life experiences had influenced my science fiction writing particularly in a way that's different from other writers'.

Q: Is it because your previous books didn't sell well enough, and the financial stability they brought you wasn't stable enough, that you didn't become a full-time writer?

A: That's one of the reasons. Writing a book a year is exhausting in terms of the normal demands of life, and there's no way to guarantee that your book will always sell. Plus, I live in a place where there are no sci-fi circles and very few people who share my passion. If I don't work, I'd be completely cut off from society. As a fiction writer, it wouldn't be a good idea to stay home all day. Thirdly, my job provides me with a very stable life.

Q: It was rumored that the power plant you work for was facing closure, and someone asked if he could reveal your living conditions, saying that he couldn't accept that someone as talented as you was living a life of despondency.

Q: When it was rumored that the power plant where you worked was facing closure, someone asked if he could tell us about your living conditions, saying that he couldn't accept that someone as talented as you was living in poverty.

A: The organization I work for is a centralized enterprise, how can I be in poverty? It is normal for the electric power system to close down a plant and build a new one. It doesn't mean that all the people in it will lose their jobs.I especially hate some people who always prefer martyrs and ascetics. I don't like martyrs and I don't want to be an ascetic. I especially like Heinlein's quote, "We write for Joe's beer money, and Joe likes his beer. It's our obligation to give him at least as much fun from our books as he'd get from a six pack." -- and the truth is, I'm not even short of that kind of money. I must be considered well off by the standard of my city, and to tell you a joke, we don't dare wear overalls on the street for fear of attracting thieves. A lot of media reporters always like to guess that this Liu Cixin must be someone curled up in a poky little house with gloomy light day and night, writing science fiction -- in fact, it's not like that, I have two suites in the city, both large, not poky.

Q: Your regular job is as a computer engineer for a power system, so what time do you generally use to write your books?

A: After work evenings, and all Sundays.

Q: What do your friends and colleagues think of your work?

Q: They don't care -- unless it becomes a bestseller and sells tens of millions of copies, then they will care. Right now they just think I'm doing some personal work in my spare time.

Q: What would you do if you were sent by Earth to make contact with extraterrestrial life?

A: I'm sure I'd be told what needs to be done.

Q: Would it be Cheng Xin or Luo Ji?

A: In terms of my values, definitely Luo.

## *Death's End* completed (2010)

Source: [《死神永生》完成_workership_新浪博客](https://blog.sina.com.cn/s/blog_540d5e800100lfwn.html), published on Sina Blog, 2010-09-02 10:19:36.

360,000 words.

At this point, all of *The Three Body Problem* trilogy is complete, three books in total, 880,000 words, a very long book.

Recently, almost every day, I received emails, text messages and phone calls, urging for the third part. For a long time, I felt that I was [like Yang Bailao, and I heard Huang Shiren's voice](https://en.wikipedia.org/wiki/The_White-Haired_Girl) from time to time: "Mr Liu, last year's debt should not pass the New Year's Eve, so why don't you sell off your daughter to cancel your debtL".

In fact, this book was not written slowly, *Dark Forest* published in 2008. Then after more than a year of time where, for external reasons, I did not write, the third part was also written about a year. Indeed, if one were to write 360,000 words of a long story, to ensure the quality, one should properly spend three to four years.

We have been calling for quality, but how does quality come? In terms of long novels, first of all, it takes time. Of course, there might be a kind of genius, who can create world classic from careless scribbling, but such a person appears once every hundred years. Ordinary authors like us take a long time to write a long novel, to build a world brick by brick, to have a long conversation with our own minds.

But even without the urging of readers, I couldn't have spent three or four years writing a full-length novel.This is a time of urgency, and the author is not exempt from it. Nowadays, the author who can stand the loneliness, as well as the man who sits still, not to say there is no such person, but they are extremely rare.

I Want to write faster for is another reason: a sense of crisis. I feel like I'm writing like a tour guide, taking readers on a tour of my own imaginary worlds. I've been leading this tour for more than ten years, but I haven't even finished half of the attractions yet, not to mention those being newly developed. So there is always some anxiety in my heart. Because I know that accidents can happen at any time: floods can block our way, our bus can be hijacked by gunmen. As an old sci-fi fan, I know that this is not an idle worry. Of all the mishaps sci-fi may encounter in the country, the most worrying is social unrest. At a meeting for *Science Fiction World* readers and writers, I told my readers and friends that sci-fi is a kind of literature for years of peace. They were all unimpressed, but it's true. Only in a stable life can we be interested in and shocked by the disasters of the world and the universe. If we ourselves live in a crisis-ridden environment, science fiction will no longer arouse our interest. As a matter of fact, two of the first three ages of Chinese science fiction were interrupted by social unrest, which is the biggest killer of science fiction.[^three-periods] Now that the calm has lasted for more than twenty years, it feels like at the grassroots level of society, some kind of spring is winding up, and the last straw that broke the camel's back could come at any time. Hopefully, this is just a science fiction fan's idle worry. I hope the peace will continue, since that would be a great blessing for science fiction.

But no matter what, we should travel faster in the world of sci-fi, and in this second life, we should have fun in time. To quote from Death's End: "A moment here; eons there.".

## The prehistoric age of the race of AI (2011)

Source: [AI种族的史前时代, 刘慈欣, 2011-02-11 01:37:00](https://web.archive.org/web/20110214060400/http://www.guokr.com/watson/article/6651)

Note: Written on the occasion of IBM Watson.

When computers were first created, their computing power far surpassed that of humans, and later they beat them at chess, recognizing human faces and understanding many languages. But even so, deep down, we still feel that we are not dealing with true intelligence. It is conceivable that even as the performance of computers continues to improve at a rapid pace, and even as their fuzzy-math-based pattern recognition and reasoning capabilities are further refined, we will still have difficulty seeing them as true AI, and we will lack a certain critical sense of being confronted with true intelligence.

Because their computational processes are inherently transparent and predictable.

It is not AI for a computer to win a game of chess against a human being, it is AI for it to lose a game of chess and then become so enraged that it electrifies the mouse and kills the human player playing the game.[^electrocution-chess]

[^electrocution-chess]: There is a persistent urban legend in China about a chess AI in the 1990s who played against a chess master three times and was defeated three times, and then electrocuted him "in a rage".

From the not-so-long history, the development of AI has roughly gone through two stages. 

The first stage is very idealistic, trying to use the software logic operation and hardware structure performance improvement to directly realize the intelligence, rather in the spirit of Genesis. With the failure of Japan's fifth-generation computer program, it was found that this would be difficult to do, at least in the foreseeable future. AI research then turned to databases and knowledge bases, a brute force strategy that attempted to realize intelligence based on the retrieval of huge amounts of data and knowledge. The prevalence of expert systems in the 1990s was the initial result of this research.

I once participated in the development of an expert system for turbines,[^turbine-AI] and what impressed me most was: in the process of constructing the knowledge base, when those human experts realized that their lifelong experience was summed up in just a few sentences, they were upset at first, but soon regained confidence, and thus found their own value, knowing that computers could not do anything great with just a few rules.  At most they could only be used as an aid for novices to learn. When the turbine system really broke down, the computers could not do much with just a few rules. They were right. It's true that those painting-by-the-book (simple, albeit complicated) things don't qualify as real intelligence, and real experience is hard to express in a knowledge base.

[^turbine-AI]: Liu Cixin's day job is electric power generation, so he is very familiar with turbines. He also has dabbled with AI since the 1990s.

But things are changing.

Looking back on my own work experience over the years, it is a process of increasing fear of IT systems. The DOS system of the 1980s was relatively reassuring, despite its rudimentary function, because it behaved in a very simple way, doing whatever it was told to do. All actions were within the bounds of predictability. The operating system at that time was more transparent, and it was said that some patient people had read through the source code of all of DOS. They could trace bugs of the program down to the assembly level. Later, however, the operating system evolved rapidly, the simple `C>` prompt became a gorgeous GUI, and the system gradually turned into a black box, with unpredictable behaviors. The IT system seemed to have grown from an innocent child to a deep schemer. By now, the system feels completely black box. It obeys only on the surface, and we do not know what it is thinking in its heart of darkness. Sometimes, the server hard disk drive sounds like a low cold laugh, and the little lights on the switches are like a million little impish eyes. When you're looking for bugs in the maze of hardware and software, it's like crawling through the slimy intestines of a monster, annoyed and desperate. There are many times when testing a piece of software to see if it is correct takes much longer than programming it, and this is especially true for software that is run online.

It should be recognized that all this is psychological, DOS system is not necessarily more stable than WIN2000 or XP, not to mention those UNIX-based Distributed control system for running power generation plants. These are from Europe, totally robust, reliable, rock-solid. Still, with the evolution of IT systems, people always feel that they gradually losing control of something.

For operating systems, not only their vast number of users, but also developers have this feeling of losing control. 

One of Microsoft's system designers said, "[The process of system development] is like being stuck in a dark, sticky quagmire, sinking no matter how hard you struggle, and controlling the whole picture is a delusion."

This may be a vision of AI in its infancy.

In fact, in essence, whether under DOS, Windows, Unix, or Linux, the behavior of the software is also transparent and predictable, theoretically. With sufficient manpower, every run of any program can be analyzed to produce an accurate process map. Theoretically, it is also possible to compile such monitoring software, which will accurately record each and every step of the operation of other software to generate a complete report of the computational process. Even the random numbers generated by the software can be predicted, because the `RANDOM()` function is pseudo-random. Even if the function is truly random, the rest of the computer process is still legible.

When the author was working on that turbine expert system, he had been asked to record the reasoning process of the system, or the process of retrieving the knowledge base. When the string of retrieval tree diagrams was displayed or printed out, both the turbine experts and those of us who programmed the program found it tedious to the extreme.

But as technology develops, the opacity and unpredictability of IT systems are increasing, and although quantitative changes have not yet produced qualitative changes, perhaps some non-von-Neumann computer systems, together with new software technologies such as evolutionary algorithms, will make this breakthrough a reality.

Here is a fundamental question: is human intelligence unpredictable in nature? In nature, macro-scale unpredictable objects, most typically chaotic systems, is the brain a chaotic system? It would not be if intelligence were truly generated by a giant interconnection of neurons, and although the number of neurons is enormous, exactly equal to the number of stars in the Milky Way, this interconnection is still inherently transparent and predictable, and theoretically allows for the precise monitoring and recording of the thought process in its entirety. But who knows what else lies beneath this giant interconnection that makes thinking a truly unpredictable process. Roger C. Penrose in *The Emperor's New Brain* argues that human intelligence is inherently impossible to reproduce by computers.

The goal of science, which is to make opaque and unpredictable nature transparent and predictable, is now engaged in a bizarre human endeavor in the field of artificial intelligence, trying to create something that is inherently opaque and unpredictable, which doesn't sound good. The day a true AI is created is the day our fears become reality, but we still relish it. It's human nature, man or woman, to want a lover whose behavior is not completely predictable -- else it would not be charming. There is a great temptation to create something higher than yourself and unpredictable, despite the possibility of being electrocuted while playing chess with it.

Looking at IBM Watson in front of us, we understand that we are in the prehistoric age of the race of AI.

## 1 and 100,000 earths (2012)

Published in the 2012 New Year Special Issue of *Weekend Pictorial*.

Compared to other animals, human babies are very fragile. While a pony can walk upright on its own within ten minutes of birth, human babies have to stay in their cradles for quite a long time, during which time it is impossible for them to survive without careful outside care. On his own, a human being can never emerge from the cradle. The reason for this phenomenon is evolutionary necessity; the human brain is larger in size, and when it is fully developed, it is difficult to be born, but only in advance, that is to say, all human babies are born prematurely.

If human civilization as a whole is regarded as a baby, then it is also a premature baby. The speed of civilization is much faster than the speed of natural evolution, and human beings actually entered modern civilization with the brains and bodies of primitive people.

A frightening question therefore arises: without outside care, would the baby of human civilization never have been able to get out of its cradle?

This seems to be a possibility now.

In the distant future, when people look back on the history from the mid-20th century to the present, all the earth-shattering events that have happened during this period will be worn down by time, and only two things, which we have neglected now, will become more and more important: firstly, mankind took the first step out of the cradle; and secondly, mankind took the step back. The importance of these two events cannot be overestimated. The year 1961, the year of Gagarin's flight into space, could replace the year of Jesus' birth as the first year of mankind; and the decline of space exploration after the Apollo moon landings would leave a trauma for mankind even worse than the expulsion from the Garden of Eden.

The late 1950s and early 1970s will be remembered as the Golden Age. Just over three years after the launch of the first artificial satellite, the first astronaut went into space, and just over seven years after that, man landed on the moon. At the time, people were inspired by the ambitious goal that in another decade or so, humans would be on Mars, and that reaching Jupiter's orbit to land on Io would not be far away. Even before that, the grandiose "Project Orion" was born, a spacecraft powered by exploding atomic bombs that could send dozens of astronauts to the outer planets at a time.

But soon after, the Apollo moon landings were canceled due to funding interruptions, and the rest of the flight program was canceled. Since then, human space exploration has been like a rock thrown up in the Earth's gravity field, reaching its peak for a short time and then plummeting. Apollo 17 last moon landing in December 1972 is an important turning point, after that, although there are still space stations and space shuttles, there are more and more all kinds of artificial satellites and the economic benefits they bring, there are flying to the exoplanet probes, but the nature of the human space business has quietly changed, the human space exploration from the eyes of the stars to the sky. The eyes of space exploration have shifted from the stars to the ground. Spaceflight before Apollo 17 was man's effort to get out of the cradle, and after that it was about getting more comfortable in the cradle. Space became a business with an economic logic. It must make a profit, and the pioneering spirit has been replaced by the shrewdness of businessmen, and the wings of the human heart have been broken.

In fact, looking back, did mankind ever really want to get out of the cradle? The driving force behind the space exploration boom in the mid-20th century was the Cold War, the fear of rivals and the desire to surpass them, and a kind of political advertisement to show power. Mankind never actually genuinely thought of space as a future home.

Now, the moon has been turned back into an inhospitable world with no human presence, the manned planetary flight programs of Russia and the United States have fizzled out, and Europe's Aurora program to explore the solar system has been put on hold, with no light in sight. After the retirement of the Space Shuttle, the Americans, who had once set foot on the Moon, even lost the ability to put people into near-Earth orbit for a long time.

Why?

Nothing but technical and economic reasons.

Let's look at the technical reasons first. It is undeniable that mankind does not currently possess the technology to carry out large-scale space development within the solar system. In the most basic and critical propulsion technology in space navigation, mankind is only at the stage of chemical propulsion, and large-scale interplanetary navigation requires nuclear propulsion, and the current technology is still far from this. Nuclear-powered rockets and spaceships are still just something in science fiction.

Then let's look at the economic reasons. With current technology, sending a payload into near-Earth orbit costs the same amount of money as the same weight of gold; sending it to the moon and other planets costs ten or even a hundred times as much. Before the industrialization of space development, all these inputs could only get very little return, for example, the Apollo moon landing project cost $26 billion, equivalent to more than $100 billion nowadays, and only got more than two tons of moon rocks. (Of course, the technological achievements of the moon landing project produced huge benefits in the subsequent civilization process, but these benefits could not be quantified, and it was impossible to be the decisive factor to be considered in the decision-making process.)

To summarize, space development is a huge risk, both technically and economically, and it is politically unacceptable to regard space as the new home of mankind and to stake the future of mankind on such a big risk.

The above reasons are solidly argued, seemingly irrefutable, and dictate the current human space policy and its resulting decline in the space business.

But let us examine the one grand enterprise in which mankind is currently fully engaged and which it sees as the only way out for the future survival of civilization on Earth: environmental protection.

From the technical point of view, space navigation and environmental protection have different colors in people's minds; the former is strenuous, high-speed and adventurous, implying cutting-edge and high technology; the latter is a kind of gentle green public welfare activities, although there is technology in it, but the difficulty is far different from the former in the impression.

But that's just a perception. In fact, the technology required to achieve humanity's current environmental protection goals is much harder than large-scale interplanetary voyages.

On a cognitive level, to protect the environment you first have to recognize it, to understand its laws on a global scale. And the Earth's ecosystem is extremely complex, and although various disciplines have made huge amounts of research and understanding of its details, at the global scale, mankind currently does not have a grasp of its laws, either at the level of basic science or applied science. There is very little that human science can know about the operation of weather systems, the changes and interrelationships of large-scale biomes, and so on.

Taking global warming as an example, is the Earth's climate really warming? If so, is the warming related to human activity? Unlike the overwhelming and unanimous propaganda, the scientific community is still inconclusive on these two crucial questions, so curbing global warming is more like a political movement. It is no exaggeration to say that mankind does not know as much about the surface of the Earth as it does about the surface of the Moon, and probably will soon know less about it than about the surface of Mars.

At the operational level, the technologies currently required for environmental protection, such as the replacement of fossil energy sources with renewable ones, the treatment and recycling of industrial and municipal waste, the preservation of biodiversity, and the protection and restoration of forest cover, involve complex technologies, a good part of which are not much easier than the technologies for interplanetary voyages within the solar system.

But the technological challenge of environmental protection is not the main one. Now that global wars and upheavals are far behind us and human society has entered a period of sustained peaceful development, especially in the Third World and underdeveloped regions, which are developing at an unprecedented rate, these fast-growing regions have the same goal: to reach the economic level of the developed Western countries and to live in the same modernized and comfortable way as they do. This does not seem to be an unattainable goal. At the current rate of development, it will take only half a century for most of the underdeveloped regions, including third world countries like China and Brazil, to catch up with the West economically.

However, people have overlooked the fact that if all human beings were to live like the developed countries of Europe and America, it would take four and a half earths to consume enough resources.

Under such circumstances, if we want to achieve the ultimate goal of environmental protection, to maintain the earth's ecology from collapse, and to control the extinction of species that is now occurring at a rate faster than the Cretaceous extinction, it is far from enough to rely only on self-discipline to reduce pollution, improve energy conservation, and emission reduction. Even if all the goals of the Copenhagen Conference are realized, the ecology of the Earth will still sink like the Titanic.

The only hope is to de-growth. But growth is unstoppable, and it is contrary to basic human values and politically unworkable for some countries and regions to allow the rest of the planet to remain in the backwardness and poverty of agrarian societies while they relax in the comfortable recliners of modern civilization.

Examine another possibility: dramatic environmental change brought about by non-human factors. The Earth's environment has always been in fluctuation, but the history of human civilization has been too short for people to notice. With each fluctuation, the Earth's environment as a whole changes drastically, and may become completely unsuitable for human survival. For example, the Last Glacial Period didn't end until 10,000 years ago, and if another ice age were to happen, the continents would be covered in ice and snow, existing global agriculture would collapse, and it would be a catastrophe for modernized societies with huge populations, and such a drastic change in the environment is almost inevitable in the long run, and there is a very high probability that it may happen in the not-too-distant future. Existing environmental protection measures are only a drop in the bucket for such environmental changes.

If human civilization is to survive man-made or natural environmental changes in the long term, it can only change its environmental protection behavior from passive to active, and artificially adjust and change the earth's environment in a holistic manner. For example, people have put forward a variety of programs to mitigate the greenhouse effect, including the establishment of a large number of giant solar evaporation stations in the ocean, the sea water evaporation sprayed into the high altitude in order to increase the amount of clouds; in the Lagrange point between the sun and the earth, the construction of a piece of the earth's umbrella with an area of three million square kilometers, etc., these projects are not unprecedented super-projects, the magnitude of its large-scale, such as the handwriting of God, the involved Technology is also the earth in the science fiction only have super technology, its difficulty is far greater than the solar system interplanetary navigation.

In addition to the technical difficulties, when we look at environmental protection from an economic point of view, we find that it is very similar to space development: both require huge upfront investments, and there is no obvious economic return at first.

However, human investment in environmental protection is disproportionately large compared to investment in space development. For example, the 12th Chinese Five-Year Plan has invested more than 3 trillion yuan in environmental protection, but only about 30 billion yuan in space exploration. The situation in the rest of the world is similar.

The solar system has a huge amount of resources, in the eight planets, in the asteroid belt, from water to metal to nuclear fusion fuel, human survival and development of all the resources needed, according to the Earth can ultimately support a population of 100 billion people calculated that the total resources in the entire solar system can support 100,000 Earth.

Now we are witnessing the fact that Humanity has given up the 100,000 Earths in space and intends to survive only on this one Earth, and the means of their survival is environmental protection, an endeavor as arduous and adventurous as space exploration.

Like environmental protection, space development interacts with technological progress, and space development promotes technological progress. Before the Apollo project, the United States did not have the technology needed to land on the moon, and a significant portion of the technology was developed in the course of the project. Nuclear fission technology has become a reality on Earth, and there are no insurmountable obstacles to the realization of nuclear propulsion in space. Although controlled nuclear fusion has not yet been realized, there are only technical obstacles rather than theoretical obstacles.

Navigation and control computers on the moon landing spacecraft more than forty years ago had only one-thousandth of the capacity of the present iPhone 4.

Space exploration is similar to the bygone Age of Sail. It is also a voyage to an unknown world to open up space for human existence and create a better life. The beginning of the Age of Sail was the discovery of the New World by Christopher Columbus, whose voyage was supported by Queen Isabella I of Spain (or more precisely, the Queen of the Kingdom of Castile, back when Spain did not exist), who herself had difficulty in paying for the fleet, and is said to have pawned all her jewelry and then supplied it to Columbus for the voyage. This has now proved to be a most judicious venture, so much so that it is said that the history of the world began in the year 1500, for it was not until that time that the whole world was known in its entirety.

Now mankind is on the eve of the second great age of navigation. We are now much luckier than Columbus. Columbus couldn't see the new continent he was looking for, he didn't see any land after sailing on the Atlantic Ocean for several days, and he must have been full of hesitation and uncertainty. The new world we want to explore can be seen when we look up, but no one has footed the bill yet.

Perhaps human civilization as a whole, like individual human babies, can really never get out of the cradle without parental help.

But from a cosmic point of view, Earth's civilization is parentless, and humanity is the orphan of the universe, so we really have to be on our best behavior.

## Book recommendations (2012)

Source: [【北京青年报】刘慈欣：科幻阶梯阅读荐书榜（菜鸟-明星-骨灰）](https://www.douban.com/group/topic/30957820/?_i=2658655pjDXMk5%2C52226749ZoyjXW)

Ladder Reading Book Recommendation List: This list introduces a reading theme every month, and recommends books around that theme, launching a basic book list from "Rookie" to "Star" or "Diehard".

This month's theme: science fiction

### Rookie

Relative to other genres, the number of original and translated science fiction novels is not very large, divided into four levels of recommendation is a bit reluctant, and can only make a rough distinction by style.

Generally speaking, early science fiction novels are more suitable for rookies, because the scientific and technological content involved in science fiction at that time is now people's common knowledge, and the threshold of reading in terms of knowledge is low. At the same time, compared with modern science fiction literature influenced by modern and postmodern styles, early science fiction focuses more on telling good stories, and the writing is clearer and more fluent.

1. Verne's science fiction novels, including *Twenty Thousand Leagues Under the Sea*, *From the Earth to the Moon*, and *Propeller Island*.

Verne's science fiction works have not yet been completely separated from the style of European adventure novels back then, but the most charming factors of science fiction literature have already appeared, science and technology as an important role for the first time in the novels, and the relationship between humans and nature instead of the relationship among humans has become the main object of depiction. Although most of the content in the novel is no longer science fiction but reality, it does not reduce the charm of the work in any way.

It should be noted that the style of Verne's work is so unique that it has hardly been reproduced in later science fiction literature.

2. Wells' science fiction novels, including *The Time Machine*, *The War of the Worlds*, *The Invisible Man*, etc.

Wells' works are much more sociologically complex than Verne's, and also subvert Verne's techno-optimism by showing anxieties about the future. In contrast to Verne, Wells had a profound influence on the development of world science fiction literature, with his depictions of aliens and time travel, etc., and his depictions of biological sciences, etc., providing the initial paradigm for subsequent science fiction.

### Star

This level implies a clear understanding of the overall contours of science fiction literature. Science fiction literature brings together works of different styles, and there is a big difference between different styles of science fiction. Professional readers should have a rough idea of the types of works they like, and the following is a list of representative works of three different styles of science fiction: 

1. *The Fountains of Paradise* (Arthur C. Clarke)

The quintessential representative of techno-science fiction, with imagination and storytelling centered on technological ideas. This genre is known as [Campbellian science fiction](https://en.wikipedia.org/wiki/John_W._Campbell), and still represents the most popularly recognized style of science fiction literature.

2. *The Martian Chronicles* (Bradbury)

High-literary sci-fi, but not as obscure and edgy as the later New Wave sci-fi, this book makes you realize how poetic and beautiful sci-fi can be.

3. *1984* (Orwell)

Science fiction with a sociological core. A panoramic description of a possible future society.

### Diehard

To be honest, I'm not sure what this level means, so I had to list some of the more out-there, avant-garde and difficult-to-read works. Sci-fi is popular literature, so there is not much written in this kind of excessively formalistic style. If you feel disconnected while reading them, it is very much because you are facing a cultural gap.

1. *Red Mars, Blue Mars, Green Mars* (Stanley Robinson)

One of the hardest sci-fi out there, like a memoir written by an engineer who experienced a mega-project first hand, describing mankind's great journey to open up a new world.

2. *The Man in the High Castle* (Philip K. Dick)

A classic of alternative history. The story is subtly detailed and seemingly static, with the background unfolding unnoticed as the story progresses.

3. *Doomsday Book* (Connie Willis)

A classic of time travel and winner of the Nebula and Hugo awards, the story advances slowly in an extremely trivial narrative, but is full of heart-stopping tension. The book depicts Europe in 1348, which was ravaged by the Black Death, and is the closest thing to an apocalyptic scenario in the history of mankind.

4. *Stranger in a Strange Land* (Heinlein)

A science fiction novel that has made countless young people crazy, but only young people in the West. To feel the charm of this book you need to cross the cultural gap, but also need to endure the author's endless preaching.

5. *Gravity's Rainbow* (Thomas Pynchon)

The mainstream literary world has a habit of robber barons: when it sees science fiction novels that excels in literature, it takes them out of science fiction literature and declares that they belong in the mainstream, and over time, science fiction settles into second- and third-rate literary status. We use the same trick, and loot science fiction out of the storehouse of mainstream literature. The book is regarded as the pinnacle of modern literature, and its content is actually quite sci-fi, with a fantastically complex plot full of technological elements such as physics, rocket engineering, advanced mathematics, and psychology, though the messy, obscure dreaming of the modern literature that follows and the length of more than 800 pages are an ordeal of reading. Other mainstream literary classics that we can loot include Lord of the Flies and A Clockwork Orange.

6. *The Red Ocean* (Han Song)[^han-song]

A magnificent and eerie epic that looks down on humanity's past, present and future from an unprecedented dimension, the reading experience is beyond imagination.

[^han-song]: Famous (by sci-fi author standards) in China, but obscure out of China. The best English-resource I know of is this: [Jia Liyuan -- Gloomy China: China's Image in Han Song's Science Fiction](https://web.archive.org/web/20231207103844/https://www.depauw.edu/sfs/backissues/119/Jia%20Liyuan.html). His style is generally hyper-violent, absurd, body-horror, posthuman, with a cyclic cosmology -- terrible things happen, and will continue to return, because it is fate. For example, *The Red Ocean* tells about a future history over a few thousand years, where human survivors of a nuclear war use genetic engineering to create aquatic humans, and at the same time build undersea cities, transforming the blue ocean into a red ocean.

## 3 billion years of struggles -- What is it all for? (2013)

Source: [刘慈欣：走了三十亿年，我们干嘛来了？](https://site.douban.com/108540/widget/notes/194865/note/462544348/)

Preface to Zhao Yang's book *Cosmos, Future Tense* (2013-07).

A rigorous study of those success-ology[^chenggongxue] books shows that most of the methods and "secrets of success" are not generically useful, because there is a sample bias: only successful cases are presented, not the failure cases. However, there are more reliable ways to achieve success, and research has shown that a person who develops a vision or ambition from an early age and works consistently toward that vision over the years is a more reliable way to achieve success. The now popular 10,000 hour rule is another way of saying this.

[^chenggongxue]: 成功学, a genre of books much like *How to Win Friends and Influence People*, focused on teaching one to achieve material success, typically through business. Extremely popular in the 2010s.

As a writer of science fiction, I tend to see all of humanity as a whole, and in the subconscious of science fiction literature, Humanity is one person. So of course we want to know what this "person" is going to do to succeed in the universe, and it stands to reason that having a vision and consistently striving toward that vision is the key to human success (or at least survival). So let's examine the human ideal, first to see what that ideal is, and then to gauge how ambitious it is.

What is the common ideal of mankind? A complex question, but one that can be answered with some certainty. Imagine a comprehensive questionnaire survey of more than six billion people around the world on this issue, like "How would you feel successful?" and the mainstream answer can be roughly determined by the statistics: to build a society that is rich in material wealth, with a democratic system, and where everyone in the world can live a happy life on both the material and the spiritual levels. There should be no problem in making such an ideal one that is recognized by all races and nations of all mankind.

Note that there is an implicit premise here: whether we talk about "society" or "the world," we are actually referring to the earth.

Scholars, politicians, and civilians alike, subconsciously seldom think beyond the orbit of the moon when they speak of "society" and "the world". The common ideal of all mankind, then, can be reduced to a single phrase: to live a good life on Earth.

In order to examine the ambitiousness of this ideal, let's set up a reference: in the backward agricultural era, the ideal of an honest, law-abiding farmer living in a remote and closed village: to cultivate his ancestral acre of land well, to keep his bed warm in winter, to marry a wife and to have three children.

This is a low enough reference point. Considering the popular joke "sheep-herding - marrying - having children - sheep-herding"[^sheep-herding-joke], it is obvious that modern people are not interested in this ideal, but full of contempt and pity for it. Then let us make a comparison. In order to quantify it, we propose:

$$\text{ambition index} = \text{radius the person is content to reach} : \text{radius the person can possibly reach}$$

[^sheep-herding-joke]: Popular joke in China: "Why do you herd sheep?" "To save money and marry a wife in the future." "What would you do if you have a wife?" "To have a baby." "What you plan to have your child do in the future?" "To herd sheep."

Let's take a look at the farmer's ambition index. According to his humble ideal, he is content to reach the distance from the village where he lives to his own field, which varies greatly from one region to another. An average of 2 kilometers is reasonable. 

Then look at the radius of the world he can reach through his efforts, according to his cultural environment. He should be able to know from the village teacher or an outsider that he lives on a big sphere called the Earth, take half of the equator circumference of 20,000 kilometers, that is, he can reach the radius of the world through his efforts. His ideal index is then 2/20000, i.e. 0.0001.

If we look at Humanity, the radius of the region in which he lives is exactly the radius of the world that the farmer knows and can reach through his efforts, i.e., 20,000 kilometers half of the circumference of the Earth's equator; and the radius of the universe that he knows, at present, is about 15 billion light-years. But to reach the other stars outside the solar system is far beyond his ability, and even now it seems likely that he will never be able to reach them, so we do not take into account the distances beyond the solar system; we do not take into account that the furthest boundary of the solar system is the Oort Cloud, which is about 1 light-year away from the Sun, and which would take more than 20,000 years at the fastest speed that his spacecraft is now capable of. It's reasonable to consider as the reachable radius as that of the Kuiper Belt in the periphery of the solar system, 20 billion kilometers, which should be reasonable, because Voyager 1 has already flown 15 billion kilometers. The ideal index for Humanity is 

$$\text{radius of earth} : \text{radius of Kuiper Belt} = 0.000001$$

Now we see that the ideal index of mankind is only 1% of that farmer, in other words, his lowly and humble ideal which makes modern people despise and pity him is actually 100 times more magnificent than the ideal of Humanity!

If put into the past, this all-too-human version of the ideal of a wife and children in a warm bed would still be reasonable. In the previous history of mankind, which was full of hunger, disease, turmoil and war, for a considerable number of years, only a little more than half of the newborn babies survived, and only a little more than half of those who did survived lived to be more than 15 years old. In most stages of the history of civilization, poverty and hunger accompanied most people, and even the author could not have enough to eat completely until he was in junior high school, and at that time I had an enviable family situation compared with other children. So in the old days, it should have been a great ideal for all mankind to seek for food and comfort.

But now it's different. Most people have enough food and clothing, and they are beginning to think of lust and the other finer things of life. About one-tenth of the earth's population is still hungry and lack of minimum health care, but modern civilization is solving poverty with unprecedented speed, and the day when poverty is eliminated is not far away. On the other hand, with the progress of society, the era of barbaric struggle for supremacy has come to an end, and universal values are more and more commonly recognized, so the possibility of a world war is rapidly decreasing. In a nutshell: mankind has settled down for the first time since coming out of Africa 200,000 years ago.

The first organic molecules that could replicate themselves were born in the turbid oceans under lightning strikes on ancient Earth, and then after more than three billion years of long and tortuous evolution, the first intelligent civilization finally appeared on Earth. Looking back at this unimaginably long road behind us, we naturally sigh with great emotion, and now it's already time to ask ourselves: after more than three billion years of walking, what the hell are we doing here?

In other words, mankind should make a greater common ambition. What this is can be revealed in different ways, scientifically and religiously, but there is one biggest and most obvious revelation: the visible universe is 15 billion light-years wide, and there is 20 billion kilometers of reachable space [within the Kuiper Belt] already, whereas we are now living within a range of only 20,000 kilometers. The earth is a grain of vibrant dust, in a vast empty expanse, as if there is a skyscraper in which only one tiny cupboard in a basement is inhabited. This great revelation has been hanging above us, a silent beckoning that has been deafening and has haunted mankind throughout its history. This revelation, like the one given by the oceans three billion years ago to the first organic molecule that could reproduce itself, has made the mission of human civilization crystal clear.

Of course, we know very well that this kind of big and empty preaching will not impress Humanity, who has become an otaku shut in a nutshell earth. He cares more about how to live a richer and more comfortable life, not how to become more successful in the cosmos. If we look at this mission from another angle, we will find that it is vital to his survival.

The Earth's ecosphere is an unstable and dynamic closed system, and like living organisms, it has a limited lifespan, as evidenced by the Biosphere 2 project in the Arizona desert. We do not perceive the aging of the Earth's ecosphere because it is too large compared to Biosphere 2, which occupies less than a kilometer of land, and whose life span is measured in geologic epochs, which, although long, will always come to an end. The earth's ecology is like a whirlpool or an isolated wave in a long river of time, and the dynamic balance can be upset at any time, and drastic changes or even collapse can occur at any time.

To take one example: a 12-meter rise or a 12-meter fall in global sea level would be a great catastrophe for the fragile modern human society. In the former case, as we all know, coastal cities and economic zones will be submerged, and the large number of people migrating inland will lead to unimaginable social upheaval and economic collapse; whereas a drop in sea level is even more frightening because the only reason for such a drop is the increase in land glaciers due to the global cooling of the climate, and in such a drastic climatic change, the global agricultural system will completely collapse, and two thirds of the existing population may die of starvation before reaching a new level of stability. Two thirds of the current population could die of starvation before a new stability is reached.

But little thought has been given to the fact that in just 20,000 years, sea level has fluctuated not by 12 meters, but by 120 meters, and that during the last ice age 20,000 years ago, global sea level was 120 meters lower than it is today! So, even without taking a very long-term view, the earth is only a temporary place to live, and the future of mankind lies in space.

To sum up, we should re-conceptualize the significance of space exploration.

The propaganda department has a knack for puffing up the significance of an otherwise commonplace event like a balloon, but when it comes to spaceflight, this knack is gone. When it comes to the significance of aerospace achievements, it is only to enhance national strength and promote economic development, specifically, to be able to forecast the weather more accurately, to have their own GPS, to have more communication bandwidth, to make tomatoes grow bigger or smaller by breeding in space, etc. In the minds of propaganda departments, the true picture of space exploration is not established.

Humanity, as a community wandering in the long river of time, is a long procession of more than six billion people. It can be divided into three categories: most are in the middle of the procession of people, do not think much, and go with the tide. Some stand vigilant on of the edge, resisting the threat from the two sides of the vast wilderness. A very small number of people, who are in the vanguard, always facing the front of the territory that no one has ever set foot on. They cut through the thorns and thistles to open up a wider living space for the community behind them. This is undoubtedly the greatest cause of all, and spaceflight is such a cause.

In the famous Soviet space movie, *Taming of the Fire* (1972), a general complains to a national leader about the space scientists who, he says, "think only of exploring the universe, not of the national interest." Now, the nation he was referring to has disappeared into the mists of history, along with its interests, and is irrelevant to all but historians, but their achievement in spaceflight have not disappeared with the nation. If mankind continues ten thousand years from now, there probably won't be any children foolish enough to ask, "Grandpa, which was the first socialist union?" But surely some child will ask, "Grandpa, who was the first to send a man out of the Earth?"

In fact, the friends I know who are engaged in the space industry do not realize the destiny of their career, and they talk about the same sweet and sour things of mundane life. For the astronauts and every citizen in the country engaged in the space industry, not realizing the nature of space will result in the loss of a great spiritual treasure.

*Cosmos, Future Tense* is precisely a book that reacquaints us with the space industry. The content of this book is rich, from the space city to planetary exploration, from the space shuttle to the space power station, from space food to astronaut psychology, covering almost all the fields of the space industry, with rich and informative technical details and a huge amount of information, told in vivid language, describing for us a grand picture of the human space industry.

But the biggest highlight of this book is also the "future tense".

Recently, it has been suggested that the advancement and popularization of IT technology has created an illusion of progress, but in fact, there have not been many breakthroughs in other technological fields other than IT since the 1960s. This situation is especially obvious in the field of spaceflight. In the decades after the moon landing, spaceflight technology has not made any major breakthroughs in most of the basic technologies, including propulsion systems, and has only been tinkered with and improved upon. *Cosmos, Future Tense* recognizes this, and describes not only what spaceflight is now, but more of what it should be and what it could be, which puts the book in a much higher perspective than other popular science works on spaceflight. These predictions of the possibilities of space technology are not science fiction, but are based on a solid scientific and technological foundation. They even gave convincing scientific explanations to the dreams of astronautics in my poorly written *The Three Body Problem* trilogy series.

*Cosmos, Future Tense* tells us that the development of the entire solar system as a home for human beings and the expansion of living space to 100,000 Earth-equivalents is not a vain dream, but a grand wish that can be realized both theoretically and technologically. If we expect Humanity's ambition to go beyond the shepherd's, this book provides scientific arguments for this ideal and boosts the confidence in opening up new worlds in the future, which is indeed the most exciting part of *Cosmos, Future Tense*.