
## Introduction

An interesting strand of argument runs through discussions on AI: whether they can be creative or not; whether we should build them to be creative or not. 

During an online discussion, I explained to someone who is confused about why people are building these art machines that are "stealing art". I explained the technological-scientific perspective on art. Their argument ran as follows:

- Machines cannot be creative. The apparent creativity is fake and mere copying.
- People build machines not because they want to make art, but because of something else. Perhaps a greed for money, a hate of artists, or some other nefarious motivation (the post is a bit vague on the precise motivation).

I tried to explain the very different perspective on the other side of the cultural divide, so that they might understand, if not to accept:

- There is no "magic". Art might feel impossible to build a machine for, but we can.
- What I cannot create, I do not understand. (Feynman quote)
- Introspection is unreliable. Asking artists how art was "really made" is not a reliable way to understand art. 
- Thus, we can build art machines, and we want to, if we are to ever understand art.

They repeated the same arguments, but more vehemently.

It was frustrating, though I was not surprised. This incident started my thinking: This is such a common response, that there is probably a psychological mechanism behind it. This essay describes some possible mechanisms.

## The self-interest theory

The self-interest theory is as follows: "It is hard to get someone to understand something if something they care about depends on their not understanding it."

## The non-truth theory

The non-truth theory states that some arguments are forever mired in the same controversies, always rehashing the same arguments, because there is no truth to be found underneath the arguments.

There are certain social functions that are best served by saying something in language that looks like they talk about objective things. You can think of this as a hack in the programming language of humans. For example, 

There are some social functions that 

## Why it seems terrible that machines might create

At the "immortal dinner party" held by Benjamin Haydon on 28 December 1817, the Romantic poet John Keats agreed with Charles Lamb that Newton “had destroyed all the poetry of the rainbow, by reducing it to the prismatic colors”. Later, Keats wrote "Lamia" that included these famous lines:

```poem
Do not all charms fly
At the mere touch of cold philosophy?
There was an awful rainbow once in heaven:
We know her woof, her texture; she is given
In the dull catalogue of common things.
Philosophy will clip an Angel's wings,
Conquer all mysteries by rule and line,
Empty the haunted air, and gnomed mine—
Unweave a rainbow, as it erewhile made
The tender-person'd Lamia melt into a shade
```

**GPT4**: Keats came up with the concept of "negative capability." This is the ability to dwell in uncertainties, mysteries, doubts, without any compulsive reaching after fact and reason. Keats valued this ability, arguing that it was central to a poet's creative process.

## Why it seems incredible that machines might create

Here, the arguments are easier to classify. It seems that there are several common mental models that people use when they think about machines that create. Using any of these would make it seem obvious that machines cannot be creative. So, I just need to classify the mental models!

### Machines as monkeys typing randomly

In Gulliver's Travels (1726) by Jonathan Swift, there was a [writing machine](https://en.wikipedia.org/wiki/The_Engine). It is a 16x16 matrix of little square blocks, with a character on each side. To use it, you turn the 32 handles randomly, then read out the few words that appeared by chance. This allowed:

> the most ignorant person, at a reasonable charge, and with a little bodily labour, might write books in philosophy, poetry, politics, laws, mathematics, and theology, without the least assistance from genius or study.

It is a clear satire, possibly of [Ramon Llull' s Thinking Machine](https://gwern.net/doc/borges/1937-borges-raymondllullsthinkingmachine.pdf) (3 concentric rotating disks that generate all possible theological arguments):

> The first of these features means that all of these attributes are inherent; the second, that they are systematically interrelated in such a way as to affirm, with impeccable orthodoxy, that glory is eternal or that eternity is glorious; that power is true, glorious, good, great, eternal, powerful, wise, free, and virtuous, or benevolently great, greatly eternal, eternally powerful, powerfully wise, wisely free, freely virtuous, virtuously truthful, etc., etc.

### Machines as pipes for the water of creativity

> It appears to me that if one wants to make progress in mathematics one should study the masters and not the pupils.

— N.H. Abel (1802–1829), quoted from an unpublished source by O. Ore in  _Niels Henrik Abel, Mathematician Extraordinary_, p. 138.

There is a common attitude that I can summarize as this: Like drawing water from the unsullied source at the mountain's peak, so is the experience of returning to the writings of the masters: clear, refreshing, and devoid of later impurities.

#### Ancient Greek theory of creativity

In ancient Greece, the Muses were considered the source of the knowledge embodied in the poetry, lyric songs, and myths that were related orally for centuries in ancient Greek culture. Homer began his Iliad with:

> Sing, Muse, the fatal wrath of Peleus' son,  
> Which to the Greeks unnumb'red evils brought,

Note that the Muses was doing the real singing, and Homer was a channel for their singing (back then, poetry was sang -- the Iliad was written down only after a few centuries). In Plato's dialog *Ion*, Socrates (perhaps a sockpuppet of Plato) argued that "it is not by art that poets compose... but by divine apportionment":

> For the poets tell us that they carry honey to us from every quarter like bees, and they fly as bees do, sipping from honey-flowing fountains in glens and gardens of the Muses. And they tell the truth. For a poet is a delicate thing, winged and sacred, and unable to create until he becomes inspired and frenzied, his mind no longer in him; as long as he keeps his hold on that, no man can compose or chant prophecy. Since, then, it is not by art that poets compose and say many beautiful things about their subjects, as you do about Homer, but by divine apportionment, they each can do well only that to which the Muse directs them-this one dithyrambs, that one odes, or encomia, or dances, or epics, or iambics-each of them worthless in respect to the others.

The same point was made repeatedly in Plato's corpus. 

> Just as the rhapsode says what he says about Homer not by art but by divine apportionment, without intelligence (Ion 534b-c, 536c, 542a), so in the Meno (gge-looa) politicians get their virtue by divine apportionment, without intelligence; they have no more wisdom than seers and soothsayers, who say many fine things but know nothing of what they say; politicians are divine and inspired like poets, and possessed by the god (Meno 9gb-e). The irrational effects of poetry and rhapsody are directly comparable to the irrational effect of vulgar politics, whose servant is vulgar rhetoric (cf. Gorgias 502C).

<small>Both quotes came from The Dialogues of Plato, Volume 3: Ion, Hippias Minor, Laches, Protagoras, translated by R. Allen. (I decided not to use one of the freely available versions since they tended to mistranslate "gods" as "God".)</small>

For example, in [Phaedrus 245a](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0174%3Atext%3DPhaedrus%3Apage%3D245), Socrates claimed that "the poetry of the sane man vanishes into nothingness before that of the inspired madmen":

> And a third kind of possession and madness comes from the Muses. This takes hold upon a gentle and pure soul, arouses it and inspires it to songs and other poetry, and thus by adorning countless deeds of the ancients educates later generations. But he who without the divine madness comes to the doors of the Muses, confident that he will be a good poet by art, meets with no success, and the poetry of the sane man vanishes into nothingness before that of the inspired madmen.

#### Later manifestations

Isaac Newton thought he was merely recovering what the ancients have known all along. His friend William Stukeley described Newton as "the Great Restorer of True Philosophy".

#### Application to machine creativity



### Machines as flowers for the DNA of creativity

From Lovelace's "Notes by the Translator":

> The Analytical Engine has no pretensions whatever to *originate* any thing. It can do whatever *we know how to order it* to perform. ([source](https://en.wikisource.org/wiki/Scientific_Memoirs/3/Sketch_of_the_Analytical_Engine_invented_by_Charles_Babbage,_Esq./Notes_by_the_Translator))

In his seminal paper "*Computing machinery and intelligence*" (1950), Alan Turing referenced Lovelace's observation as the sixth objection to the possibility that machines might think. He then objected:

> The view that machines cannot give rise to surprises is due, I believe, to a fallacy to which philosophers and mathematicians are particularly subject. This is the assumption that as soon as a fact is presented to a mind all consequences of that fact spring into the mind simultaneously with it. It is a very useful assumption under many circumstances, but one too easily forgets that it is false. ([source](https://en.wikipedia.org/wiki/Computing_Machinery_and_Intelligence#Nine_common_objections)).

Turing was led to Lovelace's objection by debates with Douglas Hartree, who in his book "Calculating Instruments and Machines" (page 70, 1949), quoted Lovelace approvingly. He objected using the phrase "electronic brain" for devices like electronic calculating machines or automatic pilots. He clarified that these machines cannot "think for themselves" and can only execute the instructions provided to them.

Thus, machines, in this view, are akin to flowers—organisms that reproduce and grow according to a predetermined genetic code but do not originate new genetic information on their own. Creativity, like DNA, must be instilled by a designer or operator, who programs the machine with the "genetic code" of what to create.

As a short etymological fun fact, the word "development" is a little capsule of the "flower for the DNA" idea:

> First use 1756, from French *développement* (“unrolling”). Compare with *envelopment* ("rolling").

The idea is that of "opening up a scroll and showing what has always been written there. In the machines' creative process can be seen as a similar "unrolling" of predetermined instructions or codes, much like the genetic "unrolling" in a blooming flower.

This is most explicitly manifest in the idea of [preformationism](https://en.wikipedia.org/wiki/Preformationism), prevalent around 17th to 18th century. It seems the same intuitive appeals of preformationism apply to Lovelace's objection.

(A brief personal anecdote: When I was a kid, I thought bus cards contained tiny compressed coins inside, and when you "beep" them, those tiny coins fall into the machine through tiny openings on the card. Preformationism in economics!)
