
## Classical thermodynamics

### Chemical equilibrium

Standard chemistry textbooks are utter nonsense when it comes to the condition for equilibrium. You usually see things like $\Delta G = 0$ for chemical reactions in open atmosphere, or $\Delta H = 0$ for chemical reactions in a sealed container in a heat bath. When I took the chemistry courses, I was terribly confused because I felt they did not make sense. I passed the exams, but only by learning to speak the right kind of nonsense. During my study of classical thermodynamics, I rederived everything for myself, and in the process finally made everything come out the right way.

To set the scene, consider a few problems in typical books on chemistry that does not make sense. For concreteness, consider a typical chemical demonstration, the dimerization reaction of 

$$2 NO_2 \to N_2 O_4$$

Now seal a certain amount of the gas inside a glass tube. Since $NO_2$ is brown, but $N_2 O_4$ is transparent, if we heat it up, the pressure would rise, forcing the reaction to go towards the $N_2O_4$ side by Le Chatelier's principle, and the glass tube would turn transparent. Putting the tube inside an ice bath would turn it brown again.

The equilibrium for reaction is typically described as follows.

Define the reaction quotient for this reaction as $Q = \frac{[N_2 O_4]}{[NO_2]^2}$. According to the standard textbook, it states that the reaction reaches equilibrium when $\Delta H = 0$, where

$$
\Delta H = \Delta H^\circ + RT \ln Q
$$

and $\Delta H^\circ$ is the change in Helmholtz energy for the reaction at the standard state. This description is nonsense.

* $Q$ is always used inside a logarithm, like $RT\ln Q$. Logarithms can *never* have a unit, even though here $Q$ has units of molar density.
* The reaction quotient's unit depends on the reaction itself. How could this possibly be true? Imagine a physical quantity $X$ that has units of meters in one problem, but units of meters$^{-3}$ in another.
* Why can't I rewrite the equation as $4 NO_2 \to 2 N_2 O_4$? This would instantly change $Q$ to $Q' = Q^2$. How could the physics of the situation depend on our convention for describing it?
* The unit for $\Delta H$ is $J/mol$, but the units for $H$ is $J$, so somehow there is an extra $mol$ appearing out of nowhere.

The real answer is as follows: 

The state of a chemical reaction system in a closed container depends on not just its temperature, but also its chemical composition. Thus, the standard state of a chemical reaction system must specify its temperature, and the concentration of all its molecules.

Consider a chemical system
$$
\sum_i x_i X_i \leftrightarrow \sum_j y_i Y_j
$$

We must *arbitrarily* fix some standard concentrations $\left[X_i\right]^o,\left[Y_j\right]^o$, then the reaction quotient **with respect to these arbitrary conventions** is

$$
\ln Q:=\sum_j \ln y_j \frac{\left[Y_j\right]}{\left[Y_j\right]^o}-\sum_i x_i \ln \frac{\left[X_i\right]}{\left[X_i\right]^o}
$$

Then, if we immerse the system in an energy and volume bath (i.e. the open air, or maybe we throw it in a plastic bag and throw it under the sea), then

$$
\frac{d G}{d \xi}=\frac{d G^{\circ}}{d \xi}+R T \ln Q
$$

is independent of our choice of standard concentrations.

## Classical statistical mechanics

Let there be an amusement park that you are going, with many amusements i. You have exactly 1 day to spend there, so you need to spend p_i of a day on amusement i.
Now your total utility at the end of the day is equal to -\sum_i p_i \ln p_i. 
Suppose that's all there is to the amusement park, then the solution is clear: you should spend an equal amount of time at each amusement. This can be proved by Lagrange multiplier. But we can also do it more intuitively as follows.
Suppose your parents gave you a schedule for your amusement. You look at the schedule and notice that p_i < p_j. You can reject the plan and say, "I can always do better just by spending equal time at i, j, even holding the other times fixed."
The proof is simple ("partial equilibrium"): If we are only allowed to trade between time at i and j (that is, we have a "partial market")
The marginal utility of amusement i is ln(1/p_i) - 1
The marginal utility of amusement j is ln(1/p_j) - 1
So, if p_i \neq p_j, then the partial market is not at partial equilibrium.
At partial equilibrium, we must have p_i = p_j

Now at general equilibrium, all partial markets must be at partial equilibrium. Thus at general equilibrium, all p_i are equal. 

Parents tell you that unfortunately there is no general equilibrium, because the amusement park is actually infinite.

Then you remembered that the amusement park has a token system: when you enter the park you would buy a certain number of tokens. Then you spend tokens at the rides. The amount of tokens spent is proportional to the time you spend in the ride.
So your parents tell you that they'll buy you a certain number of tokens $E$ at the start of the day. Then you can plan your trip yourself. Free market, indeed.
Assuming that 
The prices of amusements are 0 < E_0 < E_1 < E_2 < \cdots. Here "E_0" is the "zero-point energy", or in other words, "just relax".
You must spend exactly all your tokens. Your parents hate wastefulness and would beat you up if you don't use all the tokens.
It is possible to spend exactly all your tokens: E_0 <= E <= \max_i E_i.

Thus we have reduced the problem to
$$
\begin{cases}
\max S(p) \
\sum_i p_i \cdot 1 = 1 \
\sum_i p_i \cdot E_i = E \
\end{cases}
$$

Under these assumptions, you can calculate that there is a unique schedule that maximizes your fun, or entropy.

Now there is a slight difficulty with your previous approach. Doing partial equilibrium between 2 amusements is not possible now, because you must balance between not just time, but also tokens. Suppose you spend less time at i to spend more time at j, this might cause you to under- or over-spend your tokens. So, to make a partial equilibrium calculation, you must use at least 3 amusements, not 2.
(And you are not allowed to "just relax", since relaxing is actually "the 0th amusement", and thus it also costs you tokens and time.)
That is, you must open partial markets with i, j, k at once, and then you can run the system to partial equilibrium. This is pretty annoying. There's a better way. 
Lagrange's devil makes an apprearance!
"You can't solve the general equilibrium problem, you say? Why not try to use multivariable calculus?"
"Too annoying."
"Alright, how about I make you a deal --"
"Sorry but I don't sell my soul."
"Don't be stupid -- only something as stupid as God could still believe in souls these days! I am proposing that you trade happiness for time and for tokens. I will make a set price for time and another set price for tokens. Both prices are in units of your happiness. You can buy happiness with time, or time with happiness, also for tokens."
"Uhmm..."
"That's all that I offer. You should read up on microeconomics so you can make the right choice. See you when the day comes!" 

So the day came and the devil showed up. It gave the prices as follows:
1 unit of time = alpha unit of utility.
1 unit of token = beta unit of utility.
So you realized that you must solve the following problem

$$\max_p (S(p) - \alpha \sum_i p_i - \beta \sum_i p_i E_i)$$

And that's when you found out that your parents = Lagrange's devil = Boltzmann's devil.


You realized what a great luck you have that the devil is there -- it has split a whole general equilibrium problem into so many partial equilibria:
$$\forall i, \max_{p_i} p_i \ln \frac{1}{p_i} - \alpha p_i - \beta p_i E_i$$

So you solve the problem:
$$p_i = e^{-1-\alpha} e^{-\beta E_i}$$

After you solved the problem, you are about to go to the devil, but then the devil stopped you and asked you to not make individual trades, but make a bulk one-time trade. So you calculate $\sum_i p_i$ and $\sum_i p_i E_i$, and to your surprise, you found that they equal exactly 1 and E. That is, you actually would spend all your time and tokens without needing to trade with the devil.
"So you see? If the mortal is ready to make a trade, the devil appears..."
"But why must you appear at all, if you are not actually going to trade with me anyway?"
"And when the mortal is truly ready to make a trade, the devil disappears..."

And so you sat there looking at your two equations in strange amusement:
$$p_i = \frac{e^{-\beta E_i}}{e^{1+\alpha}}, \quad \alpha+1 = \ln\sum_i e^{-\beta E_i} , \quad E = \sum_i E_i \frac{e^{-\beta E_i}}{e^{1+\alpha}}$$
A physicist comes and points out that they are better known as
$$p_i =  \frac{e^{-\beta E_i}}{Z}, \quad Z = e^{-\beta F} = \sum_i e^{-\beta E_i}, \quad E = \sum_i p_i E_i$$
and said that $Z$ is called "partition function", $F$ is "Helmholtz free energy", and $\beta$ is "inverse temperature". 

There is just one question left to solve: why did the devil design the prices this way?
"Because I don't want you to actually be happier!" is the answer.
What did the devil mean?
Well, after doing the pointless trade, you realized that you didn't actually need the devil. But then suppose the devil suddenly increased the price of tokens, then what would you do? You would realize that you can profit by spending a little less time at amusement i, and sell both the time and the tokens you saved to the devil, and increase your happiness! Similarly for any other form of price change.

(With a little calculation, you can show that, if there exists E_i \neq E_j, then any change in devil's prices would strictly allow you to increase happiness just by changing p_i and p_j.)

Therefore, the devil knows that any price change would increase your happiness, so it chose the prices that would minimize your happiness.
"And when the mortal is truly ready to make a trade, the devil disappears..." 

