---
title: "Cybernetic artificial intelligence"
author: "Yuxi Liu"
date: "2023-12-21"
date-modified: "2023-12-21"

categories: [AI, cybernetics, math, history]
format:
    html:
        toc: true

description: "Artificial intelligence according to Norbert Wiener."
# image: "figure/"

status: "wip"
confidence: "likely"
importance: 2
---

## Cybernetics

In the creation lore of artificial intelligence, John McCarthy invented the term "artificial intelligence" to distinguish his own style from "cybernetics", which is dominated by Norbert Wiener. However, if that is the case, then we can infer that there was a real danger that artificial intelligence could be confused with Norbert Wiener's cybernetics. That is, they must have some real similarity. IF the similarity is not in style or approach (as otherwise there would be no need to distinguish the two), then the similarity must be in goal.

And indeed there is. A brief read of the introduction to Wiener's *Cybernetics* [@wienerCyberneticsControlCommunication2019] shows that he was thinking about at least 

This is a rather obscure approach and most of the references are decades-old. The main references I relied on to write this essay are [@wienerNonlinearProblemsRandom1958, Chapter 10; @wienerCyberneticsControlCommunication2019, Chapter 9; @ohaganPolynomialChaosTutorial2013; @harrisIdentificationNonlinearSystems1967].

## Polynomial chaos

## Orthogonal functions

In order to present Wiener's approach to nonlinear control theory, we need a small amount of theory of orthogonal polynomials. Specifically, we need the Hermite and Laguerre polynomials. Those are not as famous as the trigonometric functions, but they are used in the same way as the trigonometric functions in Fourier analysis. In Fourier analysis, every well-behaved (in the Fourier sense) function is decomposable as an infinite linear sum of trigonometric functions. Similarly, every well-behaved (in the Hermite sense) function is decomposable as an infinite linear sum of Hermite functions, and the same for Laguerre.

### Laguerre functions

The Laguerre polynomials are defined by
$$
L_n(x) := \sum_{k} \binom{n}{k}\frac{(-1)^k}{k!} x^k
$${#eq-laguerre}

::: {#prop-laguerre}
Theorem: The Laguerre polynomials are orthogonal in the following sense:

$$
\int_{0}^\infty e^{-x}L_m(x) L_n(x)dx = \delta_{mn}
$$
:::

::: {.proof collapse="true"}
The Laguerre polynomials are generated by the following function

$$
g(t, x) = \sum_{n=0}^\infty t^n L_n(x)=  \frac{1}{1-t} e^{-tx/(1-t)}
$$

This can be verified that the definition of $L_n$ according to the generating function $g$ and according to @eq-laguerre  both satisfy $xL_n'' + (1-x) L_n' + nL_n = 0$, and both have the same value and first derivative at $x=0$. Therefore they are equal for all $x$.[^no-details-orthogonal-polynomial]

[^no-details-orthogonal-polynomial]: Of course, this is not the most natural way to show this, but we really don't want to go into the details of orthogonal polynomial theory.
:::

Given @prop-laguerre, we can define the Laguerre functions as follows

$$
\psi_n = e^{-x/2}L_n(x)
$$

so that they are neatly orthogonal:

$$
\int_0^\infty \psi_n \psi_m = \delta_{mn}
$$ 

### Hermite functions

The Hermite polynomials are defined by

## Representing arbitrary signals: the Hermite--Laguerre expansion

A signal is a function of time, written as $x(t)$, where $t \in \R$. The signal can take value in any space, but for convenience, we will only consider the case where $x$ is real-valued. That is, we only consider functions of type $x : \R \to \R$.

In signal processing, we assume that the signal enters a black box, and comes out transformed in some way. We do not need to assume the black box is a linear function of the input, only that it is 

## Measuring the HL expansion by analog circuitry

### The Laguerre filter bank

To find the Laguerre coefficients of a signal, we need to perform a convolution. Convolutions become products after a [Laplace transform](https://en.wikipedia.org/wiki/List_of_Laplace_transforms), so we need to find the Laplace transform of the Laguerre functions $\psi_n = e^{-x/2}L_n(x)$. It is fortunately easy to compute. We simply read from a standard table:

$$
\mathcal L [t^n e^{-\alpha t}\theta(t)] = \frac{n!}{(s+\alpha)^{n+1}}
$$

where $\theta(t) = 1_{t \geq 0}$ is the zero-one step function.

Then, since the Laplace transform is linear, we have after simplification

$$
\mathcal L[\psi_n\theta] = \frac{1}{s+1/2}\left(\frac{s-1/2}{s+1/2}\right)^n
$$

This gives a simple [filter bank](https://en.wikipedia.org/wiki/Filter_bank) that constructs the Laguerre coefficients for any signal. The input signal passes through a $\frac{1}{s+1/2}$ filter, to obtain the $c_0$ coefficient, it then passes through another $\frac{s-1/2}{s+1/2}$ filter, to obtain the $c_1$ coefficient, and so on. This filter bank can be constructed with resistors and capacitors.

### The Hermite coefficient signal

For a given input signal $x : \R \to \R$, we pass it into the Laguerre filter bank. The readouts from the filter bank are the signals $c_0(t), c_1(t), ...$. They satisfy the equation

$$
x(t - \tau) = \sum_{n\geq 0} c_n(t) \psi_n(\tau), \; \forall \tau \geq 0\quad \forall t \in \R
$$

In words, at any cut-off time $t \in \R$, the signal we have seen so far is $x(t - \tau)$ with $\tau \geq 0$. This signal is then decomposable as a linear sum of Laguerre functions $\sum_{n\geq 0} c_n(t) \psi_n(\tau)$, where $c_n(t)$ are the Laguerre coefficients. The coefficients depend on the cut-off time $t$, but does not depend on $\tau$, which is not "real" time, but only a kind of "relative historical time", as we look into the past standing at time $t$.

Given this, we can then construct 

## Appendix

Wiener's terminology is occasionally obsolete, and unfortunately the subject of cybernetic artificial intelligence is essentially never updated since Wiener, so anyone trying to study the subject must contend with his publications. So here is a list of obsolete terminology and my explanations.

* shot noise, shot effect, tube noise: white noise. It is *not* [Poisson noise](https://en.wikipedia.org/wiki/Shot_noise).
* Hermite--Laguerre expansion: Given a function $x(t)$ defined on the real line, its Hermite--Laguerre expansion is obtained by [TODO]
* chaos: a generic term for randomness, or random variables. It is *not* [chaos theory](https://en.wikipedia.org/wiki/Chaos_theory).