---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=10mm
      - left=15mm
      - right=15mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertine
    colorlinks: true
    linkcolor: 'linkcolor'
    citecolor: 'citecolor'
    filecolor: 'filecolor'
    urlcolor: 'urlcolor'
    menucolor: 'menucolor'
    runcolor: 'runcolor'
    fontsize: '16'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \usepackage{wrapfig}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
        \definecolor{linkcolor}{HTML}{800006}
        \definecolor{citecolor}{HTML}{2E7E2A}
        \definecolor{filecolor}{HTML}{131877}
        \definecolor{urlcolor}{HTML}{8A0087}
        \definecolor{menucolor}{HTML}{727500}
        \definecolor{runcolor}{HTML}{137776}
---
<!-- TITLE -->
\begin{huge}\begin{center}{\bf YUXI LIU}\end{center}\end{huge}

<!-- CONTACT INFO -->
\begin{center}yuxi\_liu@berkeley.edu ∙ \href{https://yuxi-liu-wired.github.io/}{Portfolio} ∙ \href{https://github.com/yuxi-liu-wired}{Github} ∙ \href{https://www.linkedin.com/in/yuxi-liu-78b947277/}{LinkedIn}
\end{center}
\vspace{15pt}

<!-- EDUCATION: 1ST BULLET -->
\begin{large}
  {\bf EDUCATION}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf University of California, Berkeley}\end{flushleft}
    \begin{flushright}Sep 2020-Present\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}Ph.D. in Computer Science\end{flushleft}
    \begin{flushright}Berkeley, CA\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
\end{large}
* **Project**: Explaining the scaling laws of large neural networks.

\vspace{0.05cm}

<!-- EDUCATION: 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf Australian National University}\end{flushleft}
    \begin{flushright}Feb 2016-Nov 2019\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\href{https://web.archive.org/web/20161022004515/http://programsandcourses.anu.edu.au/program/ASCAD}{B.S. in Mathematics and Theoretical Physics}\end{flushleft}
    \begin{flushright}ACT, Australia\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
\end{large}

* GPA: 7.0/7.0
* Thesis: [*Beyond expectations, but within limits -- the theory of coherent risk measures*](https://archive.is/0Y5te)
* Advisor: Robert Williamson

\vspace{1.5pt}

<!-- SKILLS -->
\begin{large}{\bf SKILLS}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}
**Languages and Tools** - *proficient:* Python, PyTorch; *competent:* Bash, C, LaTeX, Git, HTML, JavaScript.

**Theoretical Background** - Reinforcement Learning, Deep Learning, Energy-Based Models, Theoretical Physics, Pure and Applied Mathematics, Mathematical Economics, History of Science and Technology

<!-- EXPERIENCE : 1ST BULLET-->
<!-- \begin{large}{\bf EXPERIENCE}\end{large}

\vspace{3pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://archive.org/}{Internet Archive}}\end{flushleft}
    \begin{flushright}Nov 2022-May 2023\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Intern, Data Science}\end
    {flushleft}\begin{flushright}Washington, D.C.\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* **Solved entity resolution problem with Gradient Boosted Trees** \href{https://alexbass.me/projects/internet_archive/}{[here]} linking sparse wikipedia references to Internet Archive Database References
* Implemented model in Python \href{https://github.com/acbass49/wiki2ia}{[here]} which, given a wikipedia reference, will return a match in the Internet Archive Database along with a probability of matching. -->

\begin{large}{\bf AWARDS}\end{large}
\vspace{3pt}
  \hrule
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://web.archive.org/web/20231106094253/https://maths.anu.edu.au/news-events/news/2019-bom-relocation-grants-msi-honours-and-hilary-booth-scholarship-recipients/}{MSI Honours Scholarship}}\end{flushleft}
    \begin{flushright}2019\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
\end{large}
* Awarded to a student in the mathematical sciences entering the final honours year in the mathematics bachelor program.

\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://web.archive.org/web/20210515205629/https://www.anu.edu.au/students/program-administration/prizes/hanna-neumann-prize-for-first-year-mathematics/}{Hanna Neumann Prize for First Year Mathematics}}\end{flushleft}
    \begin{flushright}2016\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
\end{large}
* Best aggregate results in 12 units of advanced mathematics courses.

<!-- PERSONAL PROJECTS : 1ST BULLET -->
\begin{large}
{\bf SELECTED PROJECTS}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://wikipedia.org/}{Wikipedia}}\end{flushleft}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Editor}\end{flushleft}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Wrote Wikipedia articles on various high-interest high-traffic topics as a public service to the machine learning community, such as \href{https://en.wikipedia.org/wiki/Diffusion_model}{diffusion model}, \href{https://en.wikipedia.org/wiki/Mixture_of_experts}{mixture of experts}, and \href{https://en.wikipedia.org/wiki/Generative_adversarial_network}{generative adversarial network}.